export const dersler = [
  {
    id: 'python-temelleri',
    baslik: 'Python Temelleri',
    emoji: '🐍',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 20,
    konular: ['Değişkenler', 'Listeler', 'Döngüler'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Değişkenler ve Veri Tipleri',
        aciklama: "Python'da değişken tanımlamak için tür belirtmene gerek yok.",
        kod: `# Sayısal\nyas = 28\nmaas = 8500.50\n\n# Metin\nisim = "Ali"\n\n# Mantıksal\naktif = True\n\nprint(type(yas))    # int\nprint(type(isim))   # str\nprint(type(aktif))  # bool`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'x = 10\ny = 3\nprint(x // y)',
        secenekler: ['3', '3.33', '1', '30'],
        dogru: 0,
        aciklama: '// tam bölme yapar. 10 // 3 = 3.',
      },
      {
        tip: 'eslestir',
        soru: 'Değer tiplerini eşleştir:',
        cifitler: [
          { sol: '"Merhaba"', sag: 'str' },
          { sol: '42', sag: 'int' },
          { sol: '3.14', sag: 'float' },
          { sol: 'True', sag: 'bool' },
        ],
        aciklama: 'Python 4 temel veri tipine sahip: str, int, float, bool.',
      },
      {
        tip: 'ogret',
        baslik: 'Listeler',
        aciklama: 'Liste, birden fazla değeri sıralı tutan yapı.',
        kod: `sayilar = [3, 1, 4, 1, 5]\nisimler = ["Ali", "Ayşe"]\n\nprint(isimler[0])   # Ali\nprint(isimler[-1])  # Ayşe\nprint(len(sayilar)) # 5\nsayilar.sort()\nprint(sayilar)      # [1,1,3,4,5]`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'liste = [10, 20, 30, 40, 50]\nprint(liste[-2])',
        secenekler: ['20', '40', '50', 'Hata'],
        dogru: 1,
        aciklama: 'Negatif index sondan başlar. -2 sondan ikinci eleman: 40.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Liste oluştur, eleman ekle, uzunluğunu yazdır:',
        satirlar: [
          'print(len(meyveler))',
          'meyveler = ["elma", "armut"]',
          'meyveler.append("kiraz")',
        ],
        dogru_sira: [1, 2, 0],
        aciklama: 'Önce tanımla, sonra ekle, en son yazdır.',
      },
    ],
  },
  {
    id: 'donguler-fonksiyonlar',
    baslik: 'Döngüler & Fonksiyonlar',
    emoji: '🔄',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 25,
    konular: ['for', 'while', 'def', 'return'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'for Döngüsü',
        aciklama: 'for döngüsü bir liste veya aralık üzerinde sırayla işlem yapar.',
        kod: `meyveler = ["elma", "armut", "kiraz"]\nfor meyve in meyveler:\n    print(meyve)\n\nfor i in range(5):\n    print(i, end=" ")  # 0 1 2 3 4\n\nfor i, m in enumerate(meyveler):\n    print(f"{i}: {m}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'toplam = 0\nfor i in range(1, 5):\n    toplam += i\nprint(toplam)',
        secenekler: ['10', '15', '4', '6'],
        dogru: 0,
        aciklama: 'range(1,5) → 1,2,3,4. Toplam: 1+2+3+4 = 10.',
      },
      {
        tip: 'eslestir',
        soru: 'Döngü kavramlarını eşleştir:',
        cifitler: [
          { sol: 'range(5)', sag: '0,1,2,3,4' },
          { sol: 'enumerate(liste)', sag: 'index + değer' },
          { sol: 'break', sag: 'döngüden çık' },
          { sol: 'continue', sag: 'sonraki adıma geç' },
        ],
        aciklama: 'Bu 4 kavram Python döngülerinin temelini oluşturur.',
      },
      {
        tip: 'ogret',
        baslik: 'Fonksiyonlar',
        aciklama: 'def ile tanımlanır, return ile değer döndürür.',
        kod: `def selam(isim):\n    return f"Merhaba, {isim}!"\n\nprint(selam("Ali"))   # Merhaba, Ali!\n\ndef kare(sayi, kuvvet=2):\n    return sayi ** kuvvet\n\nprint(kare(3))    # 9\nprint(kare(3, 3)) # 27`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'def topla(a, b=10):\n    return a + b\n\nprint(topla(5))',
        secenekler: ['5', '10', '15', 'Hata'],
        dogru: 2,
        aciklama: 'b verilmediğinde varsayılan 10 kullanılır. 5+10=15.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Faktöriyel hesaplayan fonksiyon yaz:',
        satirlar: [
          'return sonuc',
          'def faktoriyel(n):',
          'sonuc = 1',
          'for i in range(1, n+1):',
          '    sonuc *= i',
        ],
        dogru_sira: [1, 2, 3, 4, 0],
        aciklama: 'def → değişken → döngü → çarp → return.',
      },
    ],
  },
  {
    id: 'numpy',
    baslik: 'NumPy Temelleri',
    emoji: '🔢',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 30,
    konular: ['Array', 'Matris', 'İstatistik'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'NumPy Array',
        aciklama: "NumPy sayısal hesaplama için temel kütüphane. Array listeden çok hızlı.",
        kod: `import numpy as np\n\na = np.array([1, 2, 3, 4, 5])\nprint(a.shape)  # (5,)\nprint(a * 2)    # [2 4 6 8 10]\nprint(a + 10)   # [11 12 13 14 15]\n\nnp.zeros(5)        # [0. 0. 0. 0. 0.]\nnp.arange(0,10,2)  # [0 2 4 6 8]`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'a = np.array([2, 4, 6, 8])\nprint(a.mean())',
        secenekler: ['4.0', '5.0', '20', '24'],
        dogru: 1,
        aciklama: 'Ortalama = (2+4+6+8)/4 = 5.0',
      },
      {
        tip: 'eslestir',
        soru: 'NumPy fonksiyonlarını eşleştir:',
        cifitler: [
          { sol: 'np.zeros(3)', sag: '[0. 0. 0.]' },
          { sol: 'np.ones(3)', sag: '[1. 1. 1.]' },
          { sol: 'np.arange(3)', sag: '[0 1 2]' },
          { sol: 'np.linspace(0,1,3)', sag: '[0. 0.5 1.]' },
        ],
        aciklama: 'Bu 4 fonksiyon NumPy array oluşturmanın temel yollarıdır.',
      },
      {
        tip: 'ogret',
        baslik: 'Matris ve İstatistik',
        aciklama: '2 boyutlu array matristir.',
        kod: `M = np.array([[1,2,3],[4,5,6],[7,8,9]])\n\nprint(M.shape)       # (3,3)\nprint(M.sum())       # 45\nprint(M.sum(axis=0)) # sütun toplamları\nprint(M.sum(axis=1)) # satır toplamları\n\nveri = np.random.normal(0, 1, 1000)\nprint(veri.mean())\nprint(veri.std())`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'M = np.array([[1,2],[3,4]])\nprint(M.sum(axis=1))',
        secenekler: ['[4, 6]', '[3, 7]', '[1,2,3,4]', '[10]'],
        dogru: 1,
        aciklama: 'axis=1 satır toplamları: [1+2, 3+4] = [3, 7]',
      },
      {
        tip: 'kod_sirala',
        soru: 'NumPy ile array oluştur ve karesini al:',
        satirlar: [
          'print(a ** 2)',
          'import numpy as np',
          'a = np.zeros(5)',
        ],
        dogru_sira: [1, 2, 0],
        aciklama: 'import → array oluştur → işlem yap.',
      },
    ],
  },
  {
    id: 'pandas',
    baslik: 'Pandas ile Veri Analizi',
    emoji: '🐼',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 35,
    konular: ['DataFrame', 'Filtreleme', 'groupby'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'DataFrame Oluşturma',
        aciklama: "DataFrame pandas'ın temel yapısı. Tablo gibi düşün.",
        kod: `import pandas as pd\n\ndf = pd.DataFrame({\n    'isim': ['Ali','Ayşe','Mehmet'],\n    'yas':  [28, 34, 25],\n    'sehir': ['İzmir','İstanbul','Ankara'],\n    'maas': [8500, 12000, 7200]\n})\n\nprint(df.shape)    # (3, 4)\nprint(df.columns)\nprint(df.head(2))`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df.shape neyi döndürür?',
        secenekler: ['(sütun, satır)', '(satır, sütun)', 'Satır sayısı', 'Sütun sayısı'],
        dogru: 1,
        aciklama: 'df.shape her zaman (satır, sütun) formatında döner.',
      },
      {
        tip: 'eslestir',
        soru: 'Pandas metodlarını eşleştir:',
        cifitler: [
          { sol: 'df.head()', sag: 'İlk 5 satır' },
          { sol: 'df.describe()', sag: 'İstatistiksel özet' },
          { sol: 'df.isnull()', sag: 'Eksik değerler' },
          { sol: 'df.dtypes', sag: 'Sütun tipleri' },
        ],
        aciklama: 'Bu 4 metod DataFrame keşfinin temelini oluşturur.',
      },
      {
        tip: 'ogret',
        baslik: 'Gruplama ve Özet',
        aciklama: 'groupby ile verileri gruplara böl.',
        kod: `ozet = df.groupby('sehir').agg(\n    kisi=('isim','count'),\n    ort_maas=('maas','mean')\n).reset_index()\n\nprint(ozet)\nprint(df['maas'].describe())`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df.groupby("sehir")["maas"].mean() ne yapar?',
        secenekler: ['Tüm maaş ortalaması', 'Kişi sayısı', 'Her şehir için ort. maaş', 'Maaşa göre sırala'],
        dogru: 2,
        aciklama: 'groupby şehre göre gruplar, mean() her grubun ortalamasını alır.',
      },
      {
        tip: 'kod_sirala',
        soru: 'DataFrame oluştur ve filtrele:',
        satirlar: [
          'print(izmir)',
          'import pandas as pd',
          "df = pd.DataFrame({'sehir':['İzmir','Ankara'],'maas':[8000,7000]})",
          "izmir = df[df['sehir']=='İzmir']",
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'import → DataFrame → filtrele → yazdır.',
      },
    ],
  },
  {
    id: 'istatistik-ml',
    baslik: 'İstatistik & ML Giriş',
    emoji: '🤖',
    renk: '#E24B4A',
    bg: '#FCEBEB',
    xp: 40,
    konular: ['Dağılım', 'Train/Test', 'Model', 'R²'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Temel İstatistik',
        aciklama: 'Veri analizi istatistikle başlar.',
        kod: `import numpy as np\n\nveri = [23,25,28,22,31,27,24]\n\nprint(f"Ortalama: {np.mean(veri):.2f}")\nprint(f"Medyan:   {np.median(veri):.2f}")\nprint(f"Std:      {np.std(veri):.2f}")\nprint(f"Min/Max:  {min(veri)} / {max(veri)}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: '[1, 2, 3, 100] için ortalama 26.5, medyan 2.5.\nAykırı değer varken hangisi güvenilir?',
        secenekler: ['Ortalama', 'Medyan', 'İkisi eşit', 'Standart sapma'],
        dogru: 1,
        aciklama: 'Aykırı değer ortalamayı etkiler. Medyan daha sağlamdır.',
      },
      {
        tip: 'eslestir',
        soru: 'İstatistik kavramlarını eşleştir:',
        cifitler: [
          { sol: 'Ortalama', sag: 'Değerlerin toplamı / sayısı' },
          { sol: 'Medyan', sag: 'Ortadaki değer' },
          { sol: 'Standart sapma', sag: 'Yayılımın ölçüsü' },
          { sol: 'Varyans', sag: 'Std²' },
        ],
        aciklama: 'Bu 4 kavram temel merkezi eğilim ve yayılım ölçüleridir.',
      },
      {
        tip: 'ogret',
        baslik: 'İlk ML Modeli',
        aciklama: 'sklearn ile model kurmak 3 adım: fit → predict → score.',
        kod: `from sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nX = np.random.rand(100,1)*10\ny = 2.5*X.ravel() + np.random.randn(100)*2\n\nX_train,X_test,y_train,y_test = train_test_split(\n    X, y, test_size=0.2\n)\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nprint(f"R²: {model.score(X_test,y_test):.4f}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'R² skoru 0.92 ne anlama gelir?',
        secenekler: ['%8 doğru', "Varyansın %92'si açıklanıyor", '%92 hata', '0.92 hata'],
        dogru: 1,
        aciklama: "R² modelin varyansı açıklama oranı. 0.92 → çok iyi.",
      },
      {
        tip: 'kod_sirala',
        soru: 'ML akışını doğru sıraya koy:',
        satirlar: [
          'print(model.score(X_test,y_test))',
          'model = LinearRegression()',
          'X_train,X_test,y_train,y_test = train_test_split(X,y)',
          'model.fit(X_train, y_train)',
        ],
        dogru_sira: [2, 1, 3, 0],
        aciklama: 'böl → model → eğit → değerlendir.',
      },
    ],
  },
  {
    id: 'matplotlib-temelleri',
    baslik: 'Matplotlib Temelleri',
    emoji: '📊',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 30,
    konular: ['Figure', 'Plot', 'Bar', 'Scatter'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: "Matplotlib'e Giriş",
        aciklama: "Matplotlib Python'un en temel görselleştirme kütüphanesi. plt.plot() ile çizgi, plt.bar() ile çubuk grafik yapabilirsin.",
        kod: `import matplotlib.pyplot as plt\nimport numpy as np\n\n# Basit çizgi grafik\nx = np.linspace(0, 10, 100)\ny = np.sin(x)\n\nplt.figure(figsize=(8, 4))\nplt.plot(x, y, color='#1D9E75', linewidth=2)\nplt.title('Sinüs Dalgası')\nplt.xlabel('x')\nplt.ylabel('sin(x)')\nplt.grid(True, alpha=0.3)\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'plt.figure(figsize=(8, 4)) ne işe yarar?',
        secenekler: [
          '8 x 4 piksel boyutunda grafik oluşturur',
          '8 x 4 inç boyutunda grafik oluşturur',
          'Grafiğe 8 çizgi ve 4 nokta ekler',
          'Grafik kalitesini ayarlar',
        ],
        dogru: 1,
        aciklama: 'figsize parametresi grafiğin boyutunu inç cinsinden belirler. (genişlik, yükseklik) sırası.',
      },
      {
        tip: 'eslestir',
        soru: 'Matplotlib grafik tiplerini eşleştir:',
        cifitler: [
          { sol: 'plt.plot()', sag: 'Çizgi grafik' },
          { sol: 'plt.bar()', sag: 'Çubuk grafik' },
          { sol: 'plt.scatter()', sag: 'Nokta grafik' },
          { sol: 'plt.hist()', sag: 'Histogram' },
        ],
        aciklama: 'Her grafik tipi farklı veri yapıları için uygundur.',
      },
      {
        tip: 'ogret',
        baslik: 'Subplots ile Çoklu Grafik',
        aciklama: 'Birden fazla grafiği yan yana veya alt alta göstermek için subplot kullanılır.',
        kod: `fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n\n# Sol grafik — çubuk\nkategoriler = ['A', 'B', 'C', 'D']\ndegerler = [23, 45, 12, 67]\naxes[0].bar(kategoriler, degerler, color='#7F77DD')\naxes[0].set_title('Çubuk Grafik')\n\n# Sağ grafik — scatter\nnp.random.seed(42)\nx = np.random.randn(50)\ny = x * 2 + np.random.randn(50)\naxes[1].scatter(x, y, color='#E24B4A', alpha=0.6)\naxes[1].set_title('Scatter Plot')\n\nplt.tight_layout()\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'plt.subplots(2, 3) ne döndürür?',
        secenekler: [
          '2 satır 3 sütun = 6 grafik alanı',
          '2 + 3 = 5 grafik alanı',
          'Sadece 1 grafik',
          '23 grafik alanı',
        ],
        dogru: 0,
        aciklama: 'subplots(satır, sütun) ile ızgara şeklinde grafik alanları oluşturulur. 2x3 = 6 alan.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Basit bir çizgi grafik oluştur:',
        satirlar: [
          'plt.show()',
          'import matplotlib.pyplot as plt',
          'plt.plot([1,2,3,4], [1,4,9,16])',
          'plt.title("Kareler")',
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'import → çiz → başlık ekle → göster sırası doğru.',
      },
    ],
  },
  {
    id: 'seaborn',
    baslik: 'Seaborn ile Güzel Grafikler',
    emoji: '🎨',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 35,
    konular: ['sns', 'Dağılım', 'Heatmap', 'Pairplot'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: "Seaborn'a Giriş",
        aciklama: "Seaborn, matplotlib üzerine kurulu istatistiksel görselleştirme kütüphanesi. Daha az kodla daha güzel grafikler üretir.",
        kod: `import seaborn as sns\nimport matplotlib.pyplot as plt\nimport pandas as pd\nimport numpy as np\n\n# Örnek veri\nnp.random.seed(42)\ndf = pd.DataFrame({\n    'yas': np.random.normal(32, 8, 200),\n    'maas': np.random.normal(9000, 2000, 200),\n    'departman': np.random.choice(['IT','Pazarlama','Satış'], 200)\n})\n\n# Basit histogram\nsns.histplot(data=df, x='yas', kde=True, color='#7F77DD')\nplt.title('Yaş Dağılımı')\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'sns.histplot() ile kde=True kullanınca ne değişir?',
        secenekler: [
          'Grafik silinir',
          'Histogram üstüne yoğunluk eğrisi eklenir',
          'Renk değişir',
          'Eksik veriler doldurulur',
        ],
        dogru: 1,
        aciklama: 'KDE (Kernel Density Estimate) dağılımı pürüzsüz bir eğriyle gösterir.',
      },
      {
        tip: 'eslestir',
        soru: 'Seaborn grafik tiplerini eşleştir:',
        cifitler: [
          { sol: 'sns.boxplot()', sag: 'Kutu grafiği (IQR)' },
          { sol: 'sns.heatmap()', sag: 'Isı haritası' },
          { sol: 'sns.scatterplot()', sag: 'Nokta grafiği' },
          { sol: 'sns.barplot()', sag: 'Güven aralıklı çubuk' },
        ],
        aciklama: 'Seaborn her grafik tipi için otomatik istatistiksel özetler ekler.',
      },
      {
        tip: 'ogret',
        baslik: 'Heatmap ve Korelasyon',
        aciklama: 'Heatmap, değişkenler arası ilişkiyi renklerle gösterir. Korelasyon matrisini görselleştirmek için idealdir.',
        kod: `# Korelasyon matrisi\nnumerik_df = df[['yas', 'maas']]\nkorr = numerik_df.corr()\n\nplt.figure(figsize=(6, 4))\nsns.heatmap(\n    korr,\n    annot=True,      # değerleri yaz\n    fmt='.2f',       # 2 ondalık\n    cmap='RdYlGn',   # kırmızı→sarı→yeşil\n    center=0,        # 0 = beyaz\n    square=True\n)\nplt.title('Korelasyon Matrisi')\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Korelasyon değeri -0.85 ne anlama gelir?',
        secenekler: [
          'Güçlü pozitif ilişki',
          'İlişki yok',
          'Güçlü negatif ilişki',
          'Zayıf pozitif ilişki',
        ],
        dogru: 2,
        aciklama: '-1\'e yakın değer güçlü negatif ilişki demek. Bir değişken artınca diğeri azalıyor.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Seaborn ile boxplot oluştur:',
        satirlar: [
          'plt.show()',
          'import seaborn as sns',
          'import matplotlib.pyplot as plt',
          "sns.boxplot(data=df, x='departman', y='maas')",
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'Her iki kütüphaneyi import et, grafiği çiz, göster.',
      },
    ],
  },
  {
    id: 'hangi-grafik',
    baslik: 'Hangi Grafik Ne Zaman?',
    emoji: '🗺️',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 25,
    konular: ['Çizgi', 'Çubuk', 'Pasta', 'Scatter'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Grafik Seçimi Kriterleri',
        aciklama: "Doğru grafik seçimi verinin hikayesini doğru anlatır. Yanlış grafik yanıltır.",
        kod: `# Zaman serisi → Çizgi grafik\nplt.plot(tarihler, degerler)\n\n# Kategorik karşılaştırma → Çubuk grafik\nplt.bar(kategoriler, degerler)\n\n# İki sayısal değişken ilişkisi → Scatter\nplt.scatter(x, y)\n\n# Dağılım → Histogram\nplt.hist(veri, bins=30)\n\n# Bütün-parça ilişkisi → Pasta (dikkatli kullan!)\nplt.pie(degerler, labels=etiketler)\n\n# KURAL: Pasta grafiği 3+ kategoride okunmaz!\n# Bunun yerine yatay çubuk grafik kullan.`,
      },
      {
        tip: 'eslestir',
        soru: 'Veri tipine göre doğru grafik tipini seç:',
        cifitler: [
          { sol: 'Zaman içinde değişim', sag: 'Çizgi grafik' },
          { sol: 'İki değişken ilişkisi', sag: 'Scatter plot' },
          { sol: 'Dağılım şekli', sag: 'Histogram' },
          { sol: 'Kategoriler arası karşılaştırma', sag: 'Çubuk grafik' },
        ],
        aciklama: 'Her veri hikayesinin en uygun grafik tipi vardır.',
      },
      {
        tip: 'coktan_secmeli',
        soru: '12 aylık satış verisini göstermek istiyorsun.\nEn uygun grafik hangisi?',
        secenekler: ['Pasta grafik', 'Scatter plot', 'Çizgi grafik', 'Histogram'],
        dogru: 2,
        aciklama: 'Zaman içindeki değişimi göstermek için çizgi grafik en uygunudur. Trendi açıkça gösterir.',
      },
      {
        tip: 'ogret',
        baslik: 'Grafik Tasarım İlkeleri',
        aciklama: 'İyi görselleştirme sadece doğru grafik seçmek değil, doğru tasarlamaktır.',
        kod: `# ❌ Kötü grafik\nplt.bar(kategoriler, degerler)  # başlık yok, eksen yok\n\n# ✅ İyi grafik\nfig, ax = plt.subplots(figsize=(8, 5))\nbars = ax.barh(kategoriler, degerler,  # yatay çubuk\n               color='#1D9E75', edgecolor='none')\n\n# Değerleri çubukların ucuna yaz\nfor bar, val in zip(bars, degerler):\n    ax.text(val + 0.5, bar.get_y() + bar.get_height()/2,\n            f'{val:,}', va='center', fontsize=10)\n\nax.set_title('Ürün Satışları', fontsize=14, pad=15)\nax.set_xlabel('Satış Adedi')\nax.spines[['top','right']].set_visible(False)  # çerçeve kaldır\nplt.tight_layout()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'ax.spines[["top","right"]].set_visible(False) ne yapar?',
        secenekler: [
          'Grafiği siler',
          'Üst ve sağ çerçeve çizgilerini kaldırır',
          'Eksenleri gizler',
          'Rengi değiştirir',
        ],
        dogru: 1,
        aciklama: 'Gereksiz çerçeve çizgilerini kaldırmak grafiği daha temiz ve modern gösterir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Başlıklı ve etiketli bir çubuk grafik oluştur:',
        satirlar: [
          'plt.show()',
          'plt.title("Aylık Satışlar")',
          'import matplotlib.pyplot as plt',
          'plt.bar(["Oca","Şub","Mar"], [120, 145, 98])',
          'plt.ylabel("Satış")',
        ],
        dogru_sira: [2, 3, 1, 4, 0],
        aciklama: 'import → çiz → başlık → etiket → göster.',
      },
    ],
  },
  {
    id: 'gorsellestirme-ipuclari',
    baslik: 'Veri Görselleştirme İpuçları',
    emoji: '💡',
    renk: '#E24B4A',
    bg: '#FCEBEB',
    xp: 30,
    konular: ['Renk', 'Yazı', 'Düzen', 'Export'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Renk Paleti Seçimi',
        aciklama: "Renk sadece estetik değil, anlam taşır. Doğru renk seçimi verinin hikayesini güçlendirir.",
        kod: `import seaborn as sns\nimport matplotlib.pyplot as plt\n\n# Seaborn hazır paletleri\nprint(sns.color_palette("husl", 8))   # parlak renkler\nprint(sns.color_palette("muted", 8))  # sakin renkler\nprint(sns.color_palette("RdYlGn"))    # kırmızı→yeşil (dikkat: renk körü!)\n\n# Kategorik veri → niteliksel palet\nsns.set_palette("husl")\n\n# Sıralı veri → ardışık palet  \nsns.set_palette("Blues")\n\n# Sapma verisi (ortası 0) → ıraksak palet\nsns.set_palette("RdBu")\n\n# İpucu: Renk körü dostu palet\nCOLORS = ['#1D9E75', '#7F77DD', '#e8a04a', '#E24B4A']`,
      },
      {
        tip: 'eslestir',
        soru: 'Renk paleti tiplerini eşleştir:',
        cifitler: [
          { sol: 'Niteliksel', sag: 'Kategoriler için farklı renkler' },
          { sol: 'Ardışık', sag: 'Düşük→yüksek değer için' },
          { sol: 'Iraksak', sag: 'Orta noktadan iki yönde' },
          { sol: 'Döngüsel', sag: 'Başı = sonu olan veriler' },
        ],
        aciklama: 'Doğru palet tipi seçmek grafiğin okunabilirliğini çok artırır.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Korelasyon matrisi için en uygun renk paleti hangisi?',
        secenekler: ['Niteliksel (husl)', 'Ardışık (Blues)', 'Iraksak (RdBu)', 'Döngüsel (hsv)'],
        dogru: 2,
        aciklama: 'Korelasyon -1 ile +1 arasında değişir ve 0 merkez. Iraksak palet bu yapı için idealdir.',
      },
      {
        tip: 'ogret',
        baslik: 'Grafik Dışa Aktarma',
        aciklama: 'Grafiği yüksek kalitede kaydetmek sunum ve yayın için kritik.',
        kod: `# Yüksek kalitede kaydet\nplt.savefig(\n    'grafik.png',\n    dpi=300,           # baskı kalitesi\n    bbox_inches='tight', # kenar boşluklarını kırp\n    facecolor='white',   # arka plan beyaz\n    transparent=False    \n)\n\n# Vektörel format (ölçeklenebilir)\nplt.savefig('grafik.svg')  # web için\nplt.savefig('grafik.pdf')  # yayın için\n\n# İpucu: plt.show() ÖNCE savefig() çağır!\n# show() sonrası figür temizlenir → boş dosya!`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'plt.savefig() ve plt.show() sıralaması neden önemli?',
        secenekler: [
          'Önemli değil, sıra fark etmez',
          'show() sonra savefig() çağrılırsa boş dosya kaydedilir',
          'savefig() grafiği siler',
          'show() olmadan savefig() çalışmaz',
        ],
        dogru: 1,
        aciklama: 'plt.show() figürü ekrana çizer ve temizler. Önce savefig(), sonra show() çağrılmalıdır.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Grafiği doğru sırayla kaydet ve göster:',
        satirlar: [
          'plt.show()',
          'plt.plot([1,2,3], [4,5,6])',
          'import matplotlib.pyplot as plt',
          'plt.savefig("grafik.png", dpi=300)',
        ],
        dogru_sira: [2, 1, 3, 0],
        aciklama: 'import → çiz → kaydet → göster. Kaydetme her zaman önce!',
      },
    ],
  },
  {
    id: 'gercek-veri-gorsellestirme',
    baslik: 'Gerçek Veriyle Görselleştirme',
    emoji: '🎯',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 45,
    konular: ['EDA', 'Pandas+Matplotlib', 'Hikaye', 'Dashboard'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Keşifsel Veri Analizi (EDA)',
        aciklama: "EDA, modelleme öncesi veriyi anlamak için yapılan görsel ve istatistiksel incelemedir. Her veri bilimi projesinin ilk adımı.",
        kod: `import pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Veriyi yükle ve incele\ndf = pd.read_csv('veri.csv')\nprint(df.shape)\nprint(df.dtypes)\nprint(df.isnull().sum())\nprint(df.describe())\n\n# EDA grafiklerini tek figürde topla\nfig, axes = plt.subplots(2, 2, figsize=(12, 8))\n\nsns.histplot(df['yas'], ax=axes[0,0], kde=True)\nsns.boxplot(data=df, x='departman', y='maas', ax=axes[0,1])\nsns.scatterplot(data=df, x='yas', y='maas', ax=axes[1,0],\n                hue='departman', alpha=0.6)\nsns.heatmap(df.select_dtypes('number').corr(),\n           annot=True, ax=axes[1,1], cmap='RdYlGn')\n\nplt.suptitle('EDA Dashboard', fontsize=14, y=1.02)\nplt.tight_layout()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'EDA\'da ilk yapılması gereken nedir?',
        secenekler: [
          'Hemen model kur',
          'Veriyi görselleştir',
          "df.shape, dtypes, isnull() ile veriyi tanı",
          'Normalizasyon uygula',
        ],
        dogru: 2,
        aciklama: "EDA'nın ilk adımı veriyi tanımaktır: boyut, tipler, eksik değerler. Sonra görselleştirme gelir.",
      },
      {
        tip: 'eslestir',
        soru: 'EDA adımlarını doğru sıraya eşleştir:',
        cifitler: [
          { sol: '1. Adım', sag: 'Veri boyutu ve tipler' },
          { sol: '2. Adım', sag: 'Eksik ve aykırı değerler' },
          { sol: '3. Adım', sag: 'Dağılım grafikleri' },
          { sol: '4. Adım', sag: 'İlişki ve korelasyon' },
        ],
        aciklama: 'EDA sırası: tanı → temizle → dağılım → ilişki.',
      },
      {
        tip: 'ogret',
        baslik: 'Veriyle Hikaye Anlatmak',
        aciklama: "İyi görselleştirme bir hikaye anlatır. Başlık, alt başlık ve açıklamalar grafiği tamamlar.",
        kod: `fig, ax = plt.subplots(figsize=(10, 5))\n\n# Ana grafik\nax.plot(aylar, satis, color='#1D9E75', linewidth=2.5,\n        marker='o', markersize=6, label='2024 Satışları')\n\n# Önemli noktayı vurgula\nmax_idx = satis.index(max(satis))\nax.annotate(\n    f'Zirve: {max(satis):,} adet',\n    xy=(aylar[max_idx], max(satis)),\n    xytext=(max_idx-2, max(satis)+100),\n    arrowprops=dict(arrowstyle='->', color='#E24B4A'),\n    color='#E24B4A', fontweight='bold'\n)\n\n# Başlık ve açıklamalar\nax.set_title('2024 Yılı Aylık Satış Performansı',\n             fontsize=14, fontweight='bold', pad=15)\nax.set_xlabel('Ay')\nax.set_ylabel('Satış Adedi')\nax.spines[['top','right']].set_visible(False)\nplt.tight_layout()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'ax.annotate() fonksiyonu ne işe yarar?',
        secenekler: [
          'Eksenlere etiket ekler',
          'Grafiğe açıklama ve ok ekler',
          'Başlık ekler',
          'Rengi değiştirir',
        ],
        dogru: 1,
        aciklama: 'annotate() ile grafik üzerindeki önemli noktalara metin ve ok eklenebilir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Tam bir EDA akışı oluştur:',
        satirlar: [
          'sns.heatmap(df.corr(), annot=True)',
          'import pandas as pd, seaborn as sns',
          'print(df.isnull().sum())',
          'df = pd.read_csv("veri.csv")',
          'sns.histplot(df["hedef"], kde=True)',
        ],
        dogru_sira: [1, 3, 2, 4, 0],
        aciklama: 'import → yükle → eksik kontrol → dağılım → korelasyon sırası doğru.',
      },
    ],
  },
];
