export const dersler = [
  {
    id: 'python-temelleri',
    baslik: 'Python Temelleri',
    emoji: '🐍',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 20,
    konular: ['Değişkenler', 'Listeler', 'Döngüler'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Değişkenler ve Veri Tipleri',
        aciklama: "Python'da değişken tanımlamak için tür belirtmene gerek yok.",
        kod: `# Sayısal\nyas = 28\nmaas = 8500.50\n\n# Metin\nisim = "Ali"\n\n# Mantıksal\naktif = True\n\nprint(type(yas))    # int\nprint(type(isim))   # str\nprint(type(aktif))  # bool`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'x = 10\ny = 3\nprint(x // y)',
        secenekler: ['3', '3.33', '1', '30'],
        dogru: 0,
        aciklama: '// tam bölme yapar. 10 // 3 = 3.',
      },
      {
        tip: 'eslestir',
        soru: 'Değer tiplerini eşleştir:',
        cifitler: [
          { sol: '"Merhaba"', sag: 'str' },
          { sol: '42', sag: 'int' },
          { sol: '3.14', sag: 'float' },
          { sol: 'True', sag: 'bool' },
        ],
        aciklama: 'Python 4 temel veri tipine sahip: str, int, float, bool.',
      },
      {
        tip: 'ogret',
        baslik: 'Listeler',
        aciklama: 'Liste, birden fazla değeri sıralı tutan yapı.',
        kod: `sayilar = [3, 1, 4, 1, 5]\nisimler = ["Ali", "Ayşe"]\n\nprint(isimler[0])   # Ali\nprint(isimler[-1])  # Ayşe\nprint(len(sayilar)) # 5\nsayilar.sort()\nprint(sayilar)      # [1,1,3,4,5]`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'liste = [10, 20, 30, 40, 50]\nprint(liste[-2])',
        secenekler: ['20', '40', '50', 'Hata'],
        dogru: 1,
        aciklama: 'Negatif index sondan başlar. -2 sondan ikinci eleman: 40.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Liste oluştur, eleman ekle, uzunluğunu yazdır:',
        satirlar: [
          'print(len(meyveler))',
          'meyveler = ["elma", "armut"]',
          'meyveler.append("kiraz")',
        ],
        dogru_sira: [1, 2, 0],
        aciklama: 'Önce tanımla, sonra ekle, en son yazdır.',
      },
    ],
  },
  {
    id: 'donguler-fonksiyonlar',
    baslik: 'Döngüler & Fonksiyonlar',
    emoji: '🔄',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 25,
    konular: ['for', 'while', 'def', 'return'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'for Döngüsü',
        aciklama: 'for döngüsü bir liste veya aralık üzerinde sırayla işlem yapar.',
        kod: `meyveler = ["elma", "armut", "kiraz"]\nfor meyve in meyveler:\n    print(meyve)\n\nfor i in range(5):\n    print(i, end=" ")  # 0 1 2 3 4\n\nfor i, m in enumerate(meyveler):\n    print(f"{i}: {m}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'toplam = 0\nfor i in range(1, 5):\n    toplam += i\nprint(toplam)',
        secenekler: ['10', '15', '4', '6'],
        dogru: 0,
        aciklama: 'range(1,5) → 1,2,3,4. Toplam: 1+2+3+4 = 10.',
      },
      {
        tip: 'eslestir',
        soru: 'Döngü kavramlarını eşleştir:',
        cifitler: [
          { sol: 'range(5)', sag: '0,1,2,3,4' },
          { sol: 'enumerate(liste)', sag: 'index + değer' },
          { sol: 'break', sag: 'döngüden çık' },
          { sol: 'continue', sag: 'sonraki adıma geç' },
        ],
        aciklama: 'Bu 4 kavram Python döngülerinin temelini oluşturur.',
      },
      {
        tip: 'ogret',
        baslik: 'Fonksiyonlar',
        aciklama: 'def ile tanımlanır, return ile değer döndürür.',
        kod: `def selam(isim):\n    return f"Merhaba, {isim}!"\n\nprint(selam("Ali"))   # Merhaba, Ali!\n\ndef kare(sayi, kuvvet=2):\n    return sayi ** kuvvet\n\nprint(kare(3))    # 9\nprint(kare(3, 3)) # 27`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'def topla(a, b=10):\n    return a + b\n\nprint(topla(5))',
        secenekler: ['5', '10', '15', 'Hata'],
        dogru: 2,
        aciklama: 'b verilmediğinde varsayılan 10 kullanılır. 5+10=15.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Faktöriyel hesaplayan fonksiyon yaz:',
        satirlar: [
          'return sonuc',
          'def faktoriyel(n):',
          'sonuc = 1',
          'for i in range(1, n+1):',
          '    sonuc *= i',
        ],
        dogru_sira: [1, 2, 3, 4, 0],
        aciklama: 'def → değişken → döngü → çarp → return.',
      },
    ],
  },
  {
    id: 'numpy',
    baslik: 'NumPy Temelleri',
    emoji: '🔢',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 30,
    konular: ['Array', 'Matris', 'İstatistik'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'NumPy Array',
        aciklama: "NumPy sayısal hesaplama için temel kütüphane. Array listeden çok hızlı.",
        kod: `import numpy as np\n\na = np.array([1, 2, 3, 4, 5])\nprint(a.shape)  # (5,)\nprint(a * 2)    # [2 4 6 8 10]\nprint(a + 10)   # [11 12 13 14 15]\n\nnp.zeros(5)        # [0. 0. 0. 0. 0.]\nnp.arange(0,10,2)  # [0 2 4 6 8]`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'a = np.array([2, 4, 6, 8])\nprint(a.mean())',
        secenekler: ['4.0', '5.0', '20', '24'],
        dogru: 1,
        aciklama: 'Ortalama = (2+4+6+8)/4 = 5.0',
      },
      {
        tip: 'eslestir',
        soru: 'NumPy fonksiyonlarını eşleştir:',
        cifitler: [
          { sol: 'np.zeros(3)', sag: '[0. 0. 0.]' },
          { sol: 'np.ones(3)', sag: '[1. 1. 1.]' },
          { sol: 'np.arange(3)', sag: '[0 1 2]' },
          { sol: 'np.linspace(0,1,3)', sag: '[0. 0.5 1.]' },
        ],
        aciklama: 'Bu 4 fonksiyon NumPy array oluşturmanın temel yollarıdır.',
      },
      {
        tip: 'ogret',
        baslik: 'Matris ve İstatistik',
        aciklama: '2 boyutlu array matristir.',
        kod: `M = np.array([[1,2,3],[4,5,6],[7,8,9]])\n\nprint(M.shape)       # (3,3)\nprint(M.sum())       # 45\nprint(M.sum(axis=0)) # sütun toplamları\nprint(M.sum(axis=1)) # satır toplamları\n\nveri = np.random.normal(0, 1, 1000)\nprint(veri.mean())\nprint(veri.std())`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'M = np.array([[1,2],[3,4]])\nprint(M.sum(axis=1))',
        secenekler: ['[4, 6]', '[3, 7]', '[1,2,3,4]', '[10]'],
        dogru: 1,
        aciklama: 'axis=1 satır toplamları: [1+2, 3+4] = [3, 7]',
      },
      {
        tip: 'kod_sirala',
        soru: 'NumPy ile array oluştur ve karesini al:',
        satirlar: [
          'print(a ** 2)',
          'import numpy as np',
          'a = np.zeros(5)',
        ],
        dogru_sira: [1, 2, 0],
        aciklama: 'import → array oluştur → işlem yap.',
      },
    ],
  },
  {
    id: 'pandas',
    baslik: 'Pandas ile Veri Analizi',
    emoji: '🐼',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 35,
    konular: ['DataFrame', 'Filtreleme', 'groupby'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'DataFrame Oluşturma',
        aciklama: "DataFrame pandas'ın temel yapısı. Tablo gibi düşün.",
        kod: `import pandas as pd\n\ndf = pd.DataFrame({\n    'isim': ['Ali','Ayşe','Mehmet'],\n    'yas':  [28, 34, 25],\n    'sehir': ['İzmir','İstanbul','Ankara'],\n    'maas': [8500, 12000, 7200]\n})\n\nprint(df.shape)    # (3, 4)\nprint(df.columns)\nprint(df.head(2))`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df.shape neyi döndürür?',
        secenekler: ['(sütun, satır)', '(satır, sütun)', 'Satır sayısı', 'Sütun sayısı'],
        dogru: 1,
        aciklama: 'df.shape her zaman (satır, sütun) formatında döner.',
      },
      {
        tip: 'eslestir',
        soru: 'Pandas metodlarını eşleştir:',
        cifitler: [
          { sol: 'df.head()', sag: 'İlk 5 satır' },
          { sol: 'df.describe()', sag: 'İstatistiksel özet' },
          { sol: 'df.isnull()', sag: 'Eksik değerler' },
          { sol: 'df.dtypes', sag: 'Sütun tipleri' },
        ],
        aciklama: 'Bu 4 metod DataFrame keşfinin temelini oluşturur.',
      },
      {
        tip: 'ogret',
        baslik: 'Gruplama ve Özet',
        aciklama: 'groupby ile verileri gruplara böl.',
        kod: `ozet = df.groupby('sehir').agg(\n    kisi=('isim','count'),\n    ort_maas=('maas','mean')\n).reset_index()\n\nprint(ozet)\nprint(df['maas'].describe())`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df.groupby("sehir")["maas"].mean() ne yapar?',
        secenekler: ['Tüm maaş ortalaması', 'Kişi sayısı', 'Her şehir için ort. maaş', 'Maaşa göre sırala'],
        dogru: 2,
        aciklama: 'groupby şehre göre gruplar, mean() her grubun ortalamasını alır.',
      },
      {
        tip: 'kod_sirala',
        soru: 'DataFrame oluştur ve filtrele:',
        satirlar: [
          'print(izmir)',
          'import pandas as pd',
          "df = pd.DataFrame({'sehir':['İzmir','Ankara'],'maas':[8000,7000]})",
          "izmir = df[df['sehir']=='İzmir']",
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'import → DataFrame → filtrele → yazdır.',
      },
    ],
  },
  {
    id: 'istatistik-ml',
    baslik: 'İstatistik & ML Giriş',
    emoji: '🤖',
    renk: '#E24B4A',
    bg: '#FCEBEB',
    xp: 40,
    konular: ['Dağılım', 'Train/Test', 'Model', 'R²'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Temel İstatistik',
        aciklama: 'Veri analizi istatistikle başlar.',
        kod: `import numpy as np\n\nveri = [23,25,28,22,31,27,24]\n\nprint(f"Ortalama: {np.mean(veri):.2f}")\nprint(f"Medyan:   {np.median(veri):.2f}")\nprint(f"Std:      {np.std(veri):.2f}")\nprint(f"Min/Max:  {min(veri)} / {max(veri)}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: '[1, 2, 3, 100] için ortalama 26.5, medyan 2.5.\nAykırı değer varken hangisi güvenilir?',
        secenekler: ['Ortalama', 'Medyan', 'İkisi eşit', 'Standart sapma'],
        dogru: 1,
        aciklama: 'Aykırı değer ortalamayı etkiler. Medyan daha sağlamdır.',
      },
      {
        tip: 'eslestir',
        soru: 'İstatistik kavramlarını eşleştir:',
        cifitler: [
          { sol: 'Ortalama', sag: 'Değerlerin toplamı / sayısı' },
          { sol: 'Medyan', sag: 'Ortadaki değer' },
          { sol: 'Standart sapma', sag: 'Yayılımın ölçüsü' },
          { sol: 'Varyans', sag: 'Std²' },
        ],
        aciklama: 'Bu 4 kavram temel merkezi eğilim ve yayılım ölçüleridir.',
      },
      {
        tip: 'ogret',
        baslik: 'İlk ML Modeli',
        aciklama: 'sklearn ile model kurmak 3 adım: fit → predict → score.',
        kod: `from sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nX = np.random.rand(100,1)*10\ny = 2.5*X.ravel() + np.random.randn(100)*2\n\nX_train,X_test,y_train,y_test = train_test_split(\n    X, y, test_size=0.2\n)\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nprint(f"R²: {model.score(X_test,y_test):.4f}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'R² skoru 0.92 ne anlama gelir?',
        secenekler: ['%8 doğru', "Varyansın %92'si açıklanıyor", '%92 hata', '0.92 hata'],
        dogru: 1,
        aciklama: "R² modelin varyansı açıklama oranı. 0.92 → çok iyi.",
      },
      {
        tip: 'kod_sirala',
        soru: 'ML akışını doğru sıraya koy:',
        satirlar: [
          'print(model.score(X_test,y_test))',
          'model = LinearRegression()',
          'X_train,X_test,y_train,y_test = train_test_split(X,y)',
          'model.fit(X_train, y_train)',
        ],
        dogru_sira: [2, 1, 3, 0],
        aciklama: 'böl → model → eğit → değerlendir.',
      },
    ],
  },
  {
    id: 'matplotlib-temelleri',
    baslik: 'Matplotlib Temelleri',
    emoji: '📊',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 30,
    konular: ['Figure', 'Plot', 'Bar', 'Scatter'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: "Matplotlib'e Giriş",
        aciklama: "Matplotlib Python'un en temel görselleştirme kütüphanesi. plt.plot() ile çizgi, plt.bar() ile çubuk grafik yapabilirsin.",
        kod: `import matplotlib.pyplot as plt\nimport numpy as np\n\n# Basit çizgi grafik\nx = np.linspace(0, 10, 100)\ny = np.sin(x)\n\nplt.figure(figsize=(8, 4))\nplt.plot(x, y, color='#1D9E75', linewidth=2)\nplt.title('Sinüs Dalgası')\nplt.xlabel('x')\nplt.ylabel('sin(x)')\nplt.grid(True, alpha=0.3)\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'plt.figure(figsize=(8, 4)) ne işe yarar?',
        secenekler: [
          '8 x 4 piksel boyutunda grafik oluşturur',
          '8 x 4 inç boyutunda grafik oluşturur',
          'Grafiğe 8 çizgi ve 4 nokta ekler',
          'Grafik kalitesini ayarlar',
        ],
        dogru: 1,
        aciklama: 'figsize parametresi grafiğin boyutunu inç cinsinden belirler. (genişlik, yükseklik) sırası.',
      },
      {
        tip: 'eslestir',
        soru: 'Matplotlib grafik tiplerini eşleştir:',
        cifitler: [
          { sol: 'plt.plot()', sag: 'Çizgi grafik' },
          { sol: 'plt.bar()', sag: 'Çubuk grafik' },
          { sol: 'plt.scatter()', sag: 'Nokta grafik' },
          { sol: 'plt.hist()', sag: 'Histogram' },
        ],
        aciklama: 'Her grafik tipi farklı veri yapıları için uygundur.',
      },
      {
        tip: 'ogret',
        baslik: 'Subplots ile Çoklu Grafik',
        aciklama: 'Birden fazla grafiği yan yana veya alt alta göstermek için subplot kullanılır.',
        kod: `fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n\n# Sol grafik — çubuk\nkategoriler = ['A', 'B', 'C', 'D']\ndegerler = [23, 45, 12, 67]\naxes[0].bar(kategoriler, degerler, color='#7F77DD')\naxes[0].set_title('Çubuk Grafik')\n\n# Sağ grafik — scatter\nnp.random.seed(42)\nx = np.random.randn(50)\ny = x * 2 + np.random.randn(50)\naxes[1].scatter(x, y, color='#E24B4A', alpha=0.6)\naxes[1].set_title('Scatter Plot')\n\nplt.tight_layout()\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'plt.subplots(2, 3) ne döndürür?',
        secenekler: [
          '2 satır 3 sütun = 6 grafik alanı',
          '2 + 3 = 5 grafik alanı',
          'Sadece 1 grafik',
          '23 grafik alanı',
        ],
        dogru: 0,
        aciklama: 'subplots(satır, sütun) ile ızgara şeklinde grafik alanları oluşturulur. 2x3 = 6 alan.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Basit bir çizgi grafik oluştur:',
        satirlar: [
          'plt.show()',
          'import matplotlib.pyplot as plt',
          'plt.plot([1,2,3,4], [1,4,9,16])',
          'plt.title("Kareler")',
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'import → çiz → başlık ekle → göster sırası doğru.',
      },
    ],
  },
  {
    id: 'seaborn',
    baslik: 'Seaborn ile Güzel Grafikler',
    emoji: '🎨',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 35,
    konular: ['sns', 'Dağılım', 'Heatmap', 'Pairplot'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: "Seaborn'a Giriş",
        aciklama: "Seaborn, matplotlib üzerine kurulu istatistiksel görselleştirme kütüphanesi. Daha az kodla daha güzel grafikler üretir.",
        kod: `import seaborn as sns\nimport matplotlib.pyplot as plt\nimport pandas as pd\nimport numpy as np\n\n# Örnek veri\nnp.random.seed(42)\ndf = pd.DataFrame({\n    'yas': np.random.normal(32, 8, 200),\n    'maas': np.random.normal(9000, 2000, 200),\n    'departman': np.random.choice(['IT','Pazarlama','Satış'], 200)\n})\n\n# Basit histogram\nsns.histplot(data=df, x='yas', kde=True, color='#7F77DD')\nplt.title('Yaş Dağılımı')\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'sns.histplot() ile kde=True kullanınca ne değişir?',
        secenekler: [
          'Grafik silinir',
          'Histogram üstüne yoğunluk eğrisi eklenir',
          'Renk değişir',
          'Eksik veriler doldurulur',
        ],
        dogru: 1,
        aciklama: 'KDE (Kernel Density Estimate) dağılımı pürüzsüz bir eğriyle gösterir.',
      },
      {
        tip: 'eslestir',
        soru: 'Seaborn grafik tiplerini eşleştir:',
        cifitler: [
          { sol: 'sns.boxplot()', sag: 'Kutu grafiği (IQR)' },
          { sol: 'sns.heatmap()', sag: 'Isı haritası' },
          { sol: 'sns.scatterplot()', sag: 'Nokta grafiği' },
          { sol: 'sns.barplot()', sag: 'Güven aralıklı çubuk' },
        ],
        aciklama: 'Seaborn her grafik tipi için otomatik istatistiksel özetler ekler.',
      },
      {
        tip: 'ogret',
        baslik: 'Heatmap ve Korelasyon',
        aciklama: 'Heatmap, değişkenler arası ilişkiyi renklerle gösterir. Korelasyon matrisini görselleştirmek için idealdir.',
        kod: `# Korelasyon matrisi\nnumerik_df = df[['yas', 'maas']]\nkorr = numerik_df.corr()\n\nplt.figure(figsize=(6, 4))\nsns.heatmap(\n    korr,\n    annot=True,      # değerleri yaz\n    fmt='.2f',       # 2 ondalık\n    cmap='RdYlGn',   # kırmızı→sarı→yeşil\n    center=0,        # 0 = beyaz\n    square=True\n)\nplt.title('Korelasyon Matrisi')\nplt.show()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Korelasyon değeri -0.85 ne anlama gelir?',
        secenekler: [
          'Güçlü pozitif ilişki',
          'İlişki yok',
          'Güçlü negatif ilişki',
          'Zayıf pozitif ilişki',
        ],
        dogru: 2,
        aciklama: '-1\'e yakın değer güçlü negatif ilişki demek. Bir değişken artınca diğeri azalıyor.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Seaborn ile boxplot oluştur:',
        satirlar: [
          'plt.show()',
          'import seaborn as sns',
          'import matplotlib.pyplot as plt',
          "sns.boxplot(data=df, x='departman', y='maas')",
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'Her iki kütüphaneyi import et, grafiği çiz, göster.',
      },
    ],
  },
  {
    id: 'hangi-grafik',
    baslik: 'Hangi Grafik Ne Zaman?',
    emoji: '🗺️',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 25,
    konular: ['Çizgi', 'Çubuk', 'Pasta', 'Scatter'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Grafik Seçimi Kriterleri',
        aciklama: "Doğru grafik seçimi verinin hikayesini doğru anlatır. Yanlış grafik yanıltır.",
        kod: `# Zaman serisi → Çizgi grafik\nplt.plot(tarihler, degerler)\n\n# Kategorik karşılaştırma → Çubuk grafik\nplt.bar(kategoriler, degerler)\n\n# İki sayısal değişken ilişkisi → Scatter\nplt.scatter(x, y)\n\n# Dağılım → Histogram\nplt.hist(veri, bins=30)\n\n# Bütün-parça ilişkisi → Pasta (dikkatli kullan!)\nplt.pie(degerler, labels=etiketler)\n\n# KURAL: Pasta grafiği 3+ kategoride okunmaz!\n# Bunun yerine yatay çubuk grafik kullan.`,
      },
      {
        tip: 'eslestir',
        soru: 'Veri tipine göre doğru grafik tipini seç:',
        cifitler: [
          { sol: 'Zaman içinde değişim', sag: 'Çizgi grafik' },
          { sol: 'İki değişken ilişkisi', sag: 'Scatter plot' },
          { sol: 'Dağılım şekli', sag: 'Histogram' },
          { sol: 'Kategoriler arası karşılaştırma', sag: 'Çubuk grafik' },
        ],
        aciklama: 'Her veri hikayesinin en uygun grafik tipi vardır.',
      },
      {
        tip: 'coktan_secmeli',
        soru: '12 aylık satış verisini göstermek istiyorsun.\nEn uygun grafik hangisi?',
        secenekler: ['Pasta grafik', 'Scatter plot', 'Çizgi grafik', 'Histogram'],
        dogru: 2,
        aciklama: 'Zaman içindeki değişimi göstermek için çizgi grafik en uygunudur. Trendi açıkça gösterir.',
      },
      {
        tip: 'ogret',
        baslik: 'Grafik Tasarım İlkeleri',
        aciklama: 'İyi görselleştirme sadece doğru grafik seçmek değil, doğru tasarlamaktır.',
        kod: `# ❌ Kötü grafik\nplt.bar(kategoriler, degerler)  # başlık yok, eksen yok\n\n# ✅ İyi grafik\nfig, ax = plt.subplots(figsize=(8, 5))\nbars = ax.barh(kategoriler, degerler,  # yatay çubuk\n               color='#1D9E75', edgecolor='none')\n\n# Değerleri çubukların ucuna yaz\nfor bar, val in zip(bars, degerler):\n    ax.text(val + 0.5, bar.get_y() + bar.get_height()/2,\n            f'{val:,}', va='center', fontsize=10)\n\nax.set_title('Ürün Satışları', fontsize=14, pad=15)\nax.set_xlabel('Satış Adedi')\nax.spines[['top','right']].set_visible(False)  # çerçeve kaldır\nplt.tight_layout()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'ax.spines[["top","right"]].set_visible(False) ne yapar?',
        secenekler: [
          'Grafiği siler',
          'Üst ve sağ çerçeve çizgilerini kaldırır',
          'Eksenleri gizler',
          'Rengi değiştirir',
        ],
        dogru: 1,
        aciklama: 'Gereksiz çerçeve çizgilerini kaldırmak grafiği daha temiz ve modern gösterir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Başlıklı ve etiketli bir çubuk grafik oluştur:',
        satirlar: [
          'plt.show()',
          'plt.title("Aylık Satışlar")',
          'import matplotlib.pyplot as plt',
          'plt.bar(["Oca","Şub","Mar"], [120, 145, 98])',
          'plt.ylabel("Satış")',
        ],
        dogru_sira: [2, 3, 1, 4, 0],
        aciklama: 'import → çiz → başlık → etiket → göster.',
      },
    ],
  },
  {
    id: 'gorsellestirme-ipuclari',
    baslik: 'Veri Görselleştirme İpuçları',
    emoji: '💡',
    renk: '#E24B4A',
    bg: '#FCEBEB',
    xp: 30,
    konular: ['Renk', 'Yazı', 'Düzen', 'Export'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Renk Paleti Seçimi',
        aciklama: "Renk sadece estetik değil, anlam taşır. Doğru renk seçimi verinin hikayesini güçlendirir.",
        kod: `import seaborn as sns\nimport matplotlib.pyplot as plt\n\n# Seaborn hazır paletleri\nprint(sns.color_palette("husl", 8))   # parlak renkler\nprint(sns.color_palette("muted", 8))  # sakin renkler\nprint(sns.color_palette("RdYlGn"))    # kırmızı→yeşil (dikkat: renk körü!)\n\n# Kategorik veri → niteliksel palet\nsns.set_palette("husl")\n\n# Sıralı veri → ardışık palet  \nsns.set_palette("Blues")\n\n# Sapma verisi (ortası 0) → ıraksak palet\nsns.set_palette("RdBu")\n\n# İpucu: Renk körü dostu palet\nCOLORS = ['#1D9E75', '#7F77DD', '#e8a04a', '#E24B4A']`,
      },
      {
        tip: 'eslestir',
        soru: 'Renk paleti tiplerini eşleştir:',
        cifitler: [
          { sol: 'Niteliksel', sag: 'Kategoriler için farklı renkler' },
          { sol: 'Ardışık', sag: 'Düşük→yüksek değer için' },
          { sol: 'Iraksak', sag: 'Orta noktadan iki yönde' },
          { sol: 'Döngüsel', sag: 'Başı = sonu olan veriler' },
        ],
        aciklama: 'Doğru palet tipi seçmek grafiğin okunabilirliğini çok artırır.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Korelasyon matrisi için en uygun renk paleti hangisi?',
        secenekler: ['Niteliksel (husl)', 'Ardışık (Blues)', 'Iraksak (RdBu)', 'Döngüsel (hsv)'],
        dogru: 2,
        aciklama: 'Korelasyon -1 ile +1 arasında değişir ve 0 merkez. Iraksak palet bu yapı için idealdir.',
      },
      {
        tip: 'ogret',
        baslik: 'Grafik Dışa Aktarma',
        aciklama: 'Grafiği yüksek kalitede kaydetmek sunum ve yayın için kritik.',
        kod: `# Yüksek kalitede kaydet\nplt.savefig(\n    'grafik.png',\n    dpi=300,           # baskı kalitesi\n    bbox_inches='tight', # kenar boşluklarını kırp\n    facecolor='white',   # arka plan beyaz\n    transparent=False    \n)\n\n# Vektörel format (ölçeklenebilir)\nplt.savefig('grafik.svg')  # web için\nplt.savefig('grafik.pdf')  # yayın için\n\n# İpucu: plt.show() ÖNCE savefig() çağır!\n# show() sonrası figür temizlenir → boş dosya!`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'plt.savefig() ve plt.show() sıralaması neden önemli?',
        secenekler: [
          'Önemli değil, sıra fark etmez',
          'show() sonra savefig() çağrılırsa boş dosya kaydedilir',
          'savefig() grafiği siler',
          'show() olmadan savefig() çalışmaz',
        ],
        dogru: 1,
        aciklama: 'plt.show() figürü ekrana çizer ve temizler. Önce savefig(), sonra show() çağrılmalıdır.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Grafiği doğru sırayla kaydet ve göster:',
        satirlar: [
          'plt.show()',
          'plt.plot([1,2,3], [4,5,6])',
          'import matplotlib.pyplot as plt',
          'plt.savefig("grafik.png", dpi=300)',
        ],
        dogru_sira: [2, 1, 3, 0],
        aciklama: 'import → çiz → kaydet → göster. Kaydetme her zaman önce!',
      },
    ],
  },
  {
    id: 'gercek-veri-gorsellestirme',
    baslik: 'Gerçek Veriyle Görselleştirme',
    emoji: '🎯',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 45,
    konular: ['EDA', 'Pandas+Matplotlib', 'Hikaye', 'Dashboard'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Keşifsel Veri Analizi (EDA)',
        aciklama: "EDA, modelleme öncesi veriyi anlamak için yapılan görsel ve istatistiksel incelemedir. Her veri bilimi projesinin ilk adımı.",
        kod: `import pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Veriyi yükle ve incele\ndf = pd.read_csv('veri.csv')\nprint(df.shape)\nprint(df.dtypes)\nprint(df.isnull().sum())\nprint(df.describe())\n\n# EDA grafiklerini tek figürde topla\nfig, axes = plt.subplots(2, 2, figsize=(12, 8))\n\nsns.histplot(df['yas'], ax=axes[0,0], kde=True)\nsns.boxplot(data=df, x='departman', y='maas', ax=axes[0,1])\nsns.scatterplot(data=df, x='yas', y='maas', ax=axes[1,0],\n                hue='departman', alpha=0.6)\nsns.heatmap(df.select_dtypes('number').corr(),\n           annot=True, ax=axes[1,1], cmap='RdYlGn')\n\nplt.suptitle('EDA Dashboard', fontsize=14, y=1.02)\nplt.tight_layout()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'EDA\'da ilk yapılması gereken nedir?',
        secenekler: [
          'Hemen model kur',
          'Veriyi görselleştir',
          "df.shape, dtypes, isnull() ile veriyi tanı",
          'Normalizasyon uygula',
        ],
        dogru: 2,
        aciklama: "EDA'nın ilk adımı veriyi tanımaktır: boyut, tipler, eksik değerler. Sonra görselleştirme gelir.",
      },
      {
        tip: 'eslestir',
        soru: 'EDA adımlarını doğru sıraya eşleştir:',
        cifitler: [
          { sol: '1. Adım', sag: 'Veri boyutu ve tipler' },
          { sol: '2. Adım', sag: 'Eksik ve aykırı değerler' },
          { sol: '3. Adım', sag: 'Dağılım grafikleri' },
          { sol: '4. Adım', sag: 'İlişki ve korelasyon' },
        ],
        aciklama: 'EDA sırası: tanı → temizle → dağılım → ilişki.',
      },
      {
        tip: 'ogret',
        baslik: 'Veriyle Hikaye Anlatmak',
        aciklama: "İyi görselleştirme bir hikaye anlatır. Başlık, alt başlık ve açıklamalar grafiği tamamlar.",
        kod: `fig, ax = plt.subplots(figsize=(10, 5))\n\n# Ana grafik\nax.plot(aylar, satis, color='#1D9E75', linewidth=2.5,\n        marker='o', markersize=6, label='2024 Satışları')\n\n# Önemli noktayı vurgula\nmax_idx = satis.index(max(satis))\nax.annotate(\n    f'Zirve: {max(satis):,} adet',\n    xy=(aylar[max_idx], max(satis)),\n    xytext=(max_idx-2, max(satis)+100),\n    arrowprops=dict(arrowstyle='->', color='#E24B4A'),\n    color='#E24B4A', fontweight='bold'\n)\n\n# Başlık ve açıklamalar\nax.set_title('2024 Yılı Aylık Satış Performansı',\n             fontsize=14, fontweight='bold', pad=15)\nax.set_xlabel('Ay')\nax.set_ylabel('Satış Adedi')\nax.spines[['top','right']].set_visible(False)\nplt.tight_layout()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'ax.annotate() fonksiyonu ne işe yarar?',
        secenekler: [
          'Eksenlere etiket ekler',
          'Grafiğe açıklama ve ok ekler',
          'Başlık ekler',
          'Rengi değiştirir',
        ],
        dogru: 1,
        aciklama: 'annotate() ile grafik üzerindeki önemli noktalara metin ve ok eklenebilir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Tam bir EDA akışı oluştur:',
        satirlar: [
          'sns.heatmap(df.corr(), annot=True)',
          'import pandas as pd, seaborn as sns',
          'print(df.isnull().sum())',
          'df = pd.read_csv("veri.csv")',
          'sns.histplot(df["hedef"], kde=True)',
        ],
        dogru_sira: [1, 3, 2, 4, 0],
        aciklama: 'import → yükle → eksik kontrol → dağılım → korelasyon sırası doğru.',
      },
    ],
  },
  {
    id: 'sql-temelleri',
    baslik: 'SQL: SELECT & GROUP BY',
    emoji: '🗄️',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 35,
    konular: ['SELECT', 'WHERE', 'GROUP BY', 'HAVING'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'SELECT ve WHERE',
        aciklama: 'SQL veri analistinin en önemli becerisi. SELECT ile sütun seçer, WHERE ile filtreleme yaparsın.',
        kod: `-- Tüm sütunları getir\nSELECT * FROM musteriler;\n\n-- Belirli sütunlar\nSELECT isim, sehir, maas\nFROM calisanlar;\n\n-- Koşullu filtreleme\nSELECT isim, maas\nFROM calisanlar\nWHERE maas > 8000\n  AND sehir = 'İzmir';\n\n-- Metin filtresi\nSELECT * FROM urunler\nWHERE kategori LIKE 'Elektron%';`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'SELECT * FROM siparisler\nWHERE miktar > 100 AND durum = \'tamamlandi\';\n\nBu sorgu neyi getirir?',
        secenekler: [
          'Tüm siparişler',
          'Miktarı 100+ VE durumu tamamlandı olan siparişler',
          'Miktarı 100+ VEYA durumu tamamlandı olan siparişler',
          'Miktarı tam 100 olan siparişler',
        ],
        dogru: 1,
        aciklama: 'AND her iki koşulun aynı anda sağlanmasını gerektirir. OR ise birinin yetmesi.',
      },
      {
        tip: 'ogret',
        baslik: 'GROUP BY ve Agregasyon',
        aciklama: 'GROUP BY verileri gruplara böler. COUNT, SUM, AVG, MAX, MIN ile analiz yaparsın.',
        kod: `-- Kategoriye göre ürün sayısı\nSELECT kategori, COUNT(*) as adet\nFROM urunler\nGROUP BY kategori;\n\n-- Şehir bazında ortalama maaş\nSELECT sehir,\n       AVG(maas)  as ort_maas,\n       COUNT(*)   as kisi_sayisi,\n       MAX(maas)  as en_yuksek\nFROM calisanlar\nGROUP BY sehir\nHAVING AVG(maas) > 9000   -- grup filtreleme\nORDER BY ort_maas DESC;`,
      },
      {
        tip: 'eslestir',
        soru: 'SQL agregasyon fonksiyonlarını eşleştir:',
        cifitler: [
          { sol: 'COUNT(*)', sag: 'Satır sayısı' },
          { sol: 'AVG(sütun)', sag: 'Ortalama' },
          { sol: 'MAX(sütun)', sag: 'En büyük değer' },
          { sol: 'HAVING', sag: 'Grup koşulu' },
        ],
        aciklama: 'WHERE bireysel satırları, HAVING ise grupları filtreler. GROUP BY sonrası kullanılır.',
      },
      {
        tip: 'bosluk',
        soru: 'GROUP BY sonrası grup filtrelemek için hangi anahtar kelime kullanılır?',
        once: 'SELECT departman, AVG(maas)\nFROM calisanlar\nGROUP BY departman\n',
        secenekler: ['HAVING', 'WHERE', 'FILTER', 'LIMIT'],
        dogru: 0,
        sonra: ' AVG(maas) > 10000;',
        aciklama: 'HAVING, GROUP BY ile oluşturulan gruplara koşul koymak için kullanılır.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Departmana göre ortalama maaşı büyükten küçüğe sırala:',
        satirlar: [
          'ORDER BY ort_maas DESC;',
          'SELECT departman, AVG(maas) as ort_maas',
          'FROM calisanlar',
          'GROUP BY departman',
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'SQL klozları: SELECT → FROM → GROUP BY → ORDER BY. Bu sıra değişmez.',
      },
    ],
  },
  {
    id: 'sql-join',
    baslik: 'SQL JOIN & Window',
    emoji: '🔗',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 40,
    konular: ['INNER JOIN', 'LEFT JOIN', 'Window', 'Subquery'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'JOIN ile Tablo Birleştirme',
        aciklama: 'JOIN, iki tabloyu ortak bir sütun üzerinden birleştirir. INNER sadece eşleşenleri, LEFT JOIN ise sol tablonun tamamını getirir.',
        kod: `-- INNER JOIN: her iki tabloda da olanlar\nSELECT s.siparis_id, m.isim, s.toplam\nFROM siparisler s\nINNER JOIN musteriler m ON s.musteri_id = m.id;\n\n-- LEFT JOIN: müşterisi olmayan siparişler dahil\nSELECT m.isim, COUNT(s.siparis_id) as siparis_sayisi\nFROM musteriler m\nLEFT JOIN siparisler s ON m.id = s.musteri_id\nGROUP BY m.isim\nORDER BY siparis_sayisi DESC;`,
      },
      {
        tip: 'eslestir',
        soru: 'JOIN tiplerini eşleştir:',
        cifitler: [
          { sol: 'INNER JOIN', sag: 'Her iki tabloda eşleşenler' },
          { sol: 'LEFT JOIN', sag: 'Sol tablo tam + sağ eşleşenler' },
          { sol: 'RIGHT JOIN', sag: 'Sağ tablo tam + sol eşleşenler' },
          { sol: 'FULL JOIN', sag: 'Her iki tablo tamamı' },
        ],
        aciklama: 'En sık kullanılan INNER ve LEFT JOIN. LEFT JOIN ile eksik veriler NULL olarak gelir.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Müşteri tablosu 100, sipariş tablosu 80 kayıt içeriyor.\nLEFT JOIN kaç satır döndürebilir (en az)?',
        secenekler: ['80', '100', '180', '8000'],
        dogru: 1,
        aciklama: 'LEFT JOIN sol tablodaki tüm satırları korur. Minimum 100 satır döner; eşleşmeyen sağ değerler NULL olur.',
      },
      {
        tip: 'ogret',
        baslik: 'Window Fonksiyonlar',
        aciklama: 'Window fonksiyonlar satırları silmeden analitik hesaplar yapar. ROW_NUMBER, RANK, LAG, SUM OVER gibi ifadeler kullanılır.',
        kod: `-- Her şehirde maaş sıralaması\nSELECT isim, sehir, maas,\n       RANK() OVER (\n           PARTITION BY sehir\n           ORDER BY maas DESC\n       ) as sehir_sirasi\nFROM calisanlar;\n\n-- Kümülatif toplam\nSELECT tarih, satis,\n       SUM(satis) OVER (\n           ORDER BY tarih\n       ) as kumulatif\nFROM gunluk_satis;\n\n-- Önceki güne göre fark\nSELECT tarih, satis,\n       satis - LAG(satis, 1) OVER (ORDER BY tarih) as degisim\nFROM gunluk_satis;`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'RANK() OVER (PARTITION BY sehir ORDER BY maas DESC)\n\nBu ifade ne yapar?',
        secenekler: [
          'Tüm çalışanları maaşa göre sıralar',
          'Her şehir içinde çalışanları maaşa göre sıralar',
          'En yüksek maaşlı kişiyi siler',
          'Şehirleri maaş ortalamasına göre sıralar',
        ],
        dogru: 1,
        aciklama: 'PARTITION BY şehre göre gruplar, ORDER BY ise her grup içinde sıralama yapar. Window fonksiyonlar satırları korur.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Müşteri ve sipariş tablolarını birleştir, toplam sipariş sayısını bul:',
        satirlar: [
          'GROUP BY m.isim;',
          'LEFT JOIN siparisler s ON m.id = s.musteri_id',
          'FROM musteriler m',
          'SELECT m.isim, COUNT(s.id) as siparis_sayisi',
        ],
        dogru_sira: [3, 2, 1, 0],
        aciklama: 'SELECT → FROM → JOIN → GROUP BY sırası doğru. LEFT JOIN ile siparişi olmayan müşteriler de gelir.',
      },
    ],
  },
  {
    id: 'veri-temizleme',
    baslik: 'Veri Temizleme',
    emoji: '🧹',
    renk: '#E24B4A',
    bg: '#FCEBEB',
    xp: 35,
    konular: ['NaN', 'Aykırı Değer', 'dtype', 'Duplicate'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Eksik Değerler (NaN)',
        aciklama: 'Gerçek veri her zaman kirlidir. Eksik değerleri tespit et, strateji seç: sil veya doldur.',
        kod: `import pandas as pd\nimport numpy as np\n\ndf = pd.read_csv('veri.csv')\n\n# Eksik değerleri tespit et\nprint(df.isnull().sum())           # sütun bazında\nprint(df.isnull().mean() * 100)   # yüzde olarak\n\n# Silme stratejisi\ndf_temiz = df.dropna()            # herhangi NaN → sil\ndf_temiz = df.dropna(subset=['maas'])  # sadece maas NaN → sil\n\n# Doldurma stratejisi\ndf['maas'].fillna(df['maas'].median(), inplace=True)  # medyan\ndf['sehir'].fillna('Bilinmiyor', inplace=True)        # sabit değer\ndf['satis'].fillna(method='ffill', inplace=True)      # önceki değer`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Maaş sütununda %30 eksik değer var.\nEn doğru yaklaşım hangisi?',
        secenekler: [
          'dropna() ile tüm satırları sil',
          'Medyan veya model tahminle doldur, nedenini belgele',
          'Sıfır ile doldur',
          'Sütunu tamamen sil',
        ],
        dogru: 1,
        aciklama: '%30 veri kaybı kabul edilemez. Medyan ile doldurmak aykırı değerlere dayanıklıdır. Her zaman kararını belgele.',
      },
      {
        tip: 'ogret',
        baslik: 'Aykırı Değerler ve Tipler',
        aciklama: 'Aykırı değerler modeli bozar. IQR yöntemi veya z-skoru ile tespit edebilirsin. dtype hatalarını düzelt.',
        kod: `# IQR yöntemi ile aykırı değer tespiti\nQ1 = df['maas'].quantile(0.25)\nQ3 = df['maas'].quantile(0.75)\nIQR = Q3 - Q1\n\nalt = Q1 - 1.5 * IQR\nust = Q3 + 1.5 * IQR\n\naykiri = df[(df['maas'] < alt) | (df['maas'] > ust)]\nprint(f"{len(aykiri)} aykırı değer bulundu")\n\n# Clip ile sınırla (silmek yerine)\ndf['maas'] = df['maas'].clip(lower=alt, upper=ust)\n\n# Tip dönüşümleri\ndf['tarih']  = pd.to_datetime(df['tarih'])\ndf['fiyat']  = pd.to_numeric(df['fiyat'], errors='coerce')\ndf['yas']    = df['yas'].astype(int)\ndf['sehir']  = df['sehir'].astype('category')  # bellek tasarrufu`,
      },
      {
        tip: 'eslestir',
        soru: 'Veri temizleme yöntemlerini eşleştir:',
        cifitler: [
          { sol: 'dropna()', sag: 'NaN satırları sil' },
          { sol: 'fillna(median)', sag: 'Medyanla doldur' },
          { sol: 'clip(lower, upper)', sag: 'Aykırı değeri sınırla' },
          { sol: 'astype("category")', sag: 'Bellek optimizasyonu' },
        ],
        aciklama: 'Her yöntemin farklı bir kullanım amacı var. Silmek veri kaybeder, doldurmak bias ekleyebilir.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df.duplicated().sum() → 45 çıktı.\ndf.drop_duplicates(inplace=True) sonrası ne olur?',
        secenekler: [
          '45 yeni satır eklenir',
          '45 duplicate satır silinir',
          'DataFrame sıfırlanır',
          'Hata verir',
        ],
        dogru: 1,
        aciklama: 'drop_duplicates() tekrar eden satırları temizler. inplace=True orijinal df\'yi değiştirir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Veri temizleme akışını doğru sıraya koy:',
        satirlar: [
          'df["fiyat"] = pd.to_numeric(df["fiyat"], errors="coerce")',
          'df.drop_duplicates(inplace=True)',
          'print(df.isnull().sum())',
          'df["fiyat"].fillna(df["fiyat"].median(), inplace=True)',
        ],
        dogru_sira: [2, 1, 0, 3],
        aciklama: 'Önce tespit et, duplicate temizle, tip düzelt, sonra eksikleri doldur.',
      },
    ],
  },
  {
    id: 'feature-engineering',
    baslik: 'Feature Engineering',
    emoji: '⚙️',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 40,
    konular: ['Encoding', 'Scaling', 'Yeni Özellik', 'Seçim'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Encoding: Kategorik → Sayısal',
        aciklama: 'ML modelleri sayısal veri ister. Kategorik değişkenleri encoding ile dönüştürmek zorundasın.',
        kod: `import pandas as pd\nfrom sklearn.preprocessing import LabelEncoder\n\ndf = pd.DataFrame({\n    'sehir':  ['İzmir','İstanbul','Ankara','İzmir'],\n    'seviye': ['Junior','Senior','Mid','Senior'],\n    'maas':   [7000, 15000, 10000, 7500]\n})\n\n# Label Encoding (sıralı kategoriler için)\nle = LabelEncoder()\ndf['seviye_enc'] = le.fit_transform(df['seviye'])\n# Junior=0, Mid=1, Senior=2\n\n# One-Hot Encoding (sırasız kategoriler için)\ndf = pd.get_dummies(df, columns=['sehir'], drop_first=True)\nprint(df.head())`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Şehir sütunu için hangi encoding kullanılmalıdır?\n(İzmir, İstanbul, Ankara — aralarında sıra yok)',
        secenekler: [
          'Label Encoding — 0, 1, 2 ver',
          'One-Hot Encoding — her şehir için ayrı sütun',
          'Ordinal Encoding — sıralı yap',
          'Encoding gerekmez',
        ],
        dogru: 1,
        aciklama: 'Sırasız kategorilerde Label Encoding yapay sıra yaratır (İzmir=0 < İstanbul=1 gibi). One-Hot Encoding bu hatayı önler.',
      },
      {
        tip: 'ogret',
        baslik: 'Ölçekleme (Scaling)',
        aciklama: 'Farklı ölçeklerdeki özellikler modeli bozar. StandardScaler veya MinMaxScaler kullanılır.',
        kod: `from sklearn.preprocessing import StandardScaler, MinMaxScaler\nimport numpy as np\n\nX = np.array([[1000, 28], [50000, 45], [15000, 32]])\n# Maaş 1000-50000, Yaş 28-45 → farklı ölçek!\n\n# StandardScaler: ortalama=0, std=1\nscaler = StandardScaler()\nX_std = scaler.fit_transform(X)\nprint("Std ortalama:", X_std.mean(axis=0))  # ~[0, 0]\nprint("Std std:",      X_std.std(axis=0))   # ~[1, 1]\n\n# MinMaxScaler: 0-1 arası\nmm = MinMaxScaler()\nX_mm = mm.fit_transform(X)\nprint(X_mm)  # her sütun 0-1 arası`,
      },
      {
        tip: 'eslestir',
        soru: 'Ölçekleme yöntemlerini eşleştir:',
        cifitler: [
          { sol: 'StandardScaler', sag: 'Ortalama=0, Std=1' },
          { sol: 'MinMaxScaler', sag: '0 ile 1 arasına sıkıştır' },
          { sol: 'fit_transform()', sag: 'Öğren ve uygula' },
          { sol: 'transform()', sag: 'Sadece uygula (test için)' },
        ],
        aciklama: 'Kritik: fit() sadece eğitim verisine uygulanır! Test verisine transform() ile aynı scaler uygulanır.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Neden test verisine fit_transform() değil, sadece transform() uygulamalısın?',
        secenekler: [
          'transform() daha hızlıdır',
          'Test seti istatistiklerinin modeli etkilememesi için (data leakage önleme)',
          'fit_transform() test setinde çalışmaz',
          'Fark yoktur',
        ],
        dogru: 1,
        aciklama: 'Scaler\'ı test verisiyle fit edersen, test seti bilgisi model eğitimine sızar (data leakage). Bu gerçekçi olmayan performans verir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Encoding ve scaling pipeline\'ı doğru sıraya koy:',
        satirlar: [
          'X_train_sc = scaler.fit_transform(X_train)',
          'X = pd.get_dummies(df, columns=["sehir"])',
          'X_test_sc = scaler.transform(X_test)',
          'X_train, X_test = train_test_split(X, y)',
        ],
        dogru_sira: [1, 3, 0, 2],
        aciklama: 'Encoding → train/test böl → scaler\'ı train\'e fit et → test\'e sadece transform.',
      },
    ],
  },
  {
    id: 'siniflandirma',
    baslik: 'Sınıflandırma Modelleri',
    emoji: '🤖',
    renk: '#E24B4A',
    bg: '#FCEBEB',
    xp: 45,
    konular: ['Lojistik Regresyon', 'Decision Tree', 'Predict', 'Proba'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Lojistik Regresyon',
        aciklama: 'Adı "regresyon" ama sınıflandırma modeli! Sigmoid fonksiyon ile 0-1 arası olasılık üretir.',
        kod: `from sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nimport pandas as pd\n\n# Churn tahmini\nX = df[['yas', 'maas', 'hizmet_yili']]\ny = df['churn']  # 0 veya 1\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)\n\nmodel = LogisticRegression(max_iter=1000)\nmodel.fit(X_train, y_train)\n\ny_pred = model.predict(X_test)\ny_proba = model.predict_proba(X_test)[:, 1]  # churn olasılığı\n\nprint(f"Accuracy: {accuracy_score(y_test, y_pred):.3f}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'model.predict_proba(X_test)[:, 1] ne döndürür?',
        secenekler: [
          'Tahmin edilen sınıf etiketleri (0 veya 1)',
          'Her örneğin "1" sınıfına ait olma olasılığı',
          'Model accuracy değeri',
          'Eğitim verisi tahminleri',
        ],
        dogru: 1,
        aciklama: 'predict_proba() iki sütun döndürür: [:,0] sınıf-0 olasılığı, [:,1] sınıf-1 olasılığı. ROC eğrisi için kullanılır.',
      },
      {
        tip: 'ogret',
        baslik: 'Decision Tree ile Sınıflandırma',
        aciklama: 'Decision Tree verileri if-else ağacıyla böler. Yorumlanabilirliği çok yüksek ama overfitting\'e meyilli.',
        kod: `from sklearn.tree import DecisionTreeClassifier\nfrom sklearn.tree import export_text\n\n# Derinliği sınırla — overfitting önle\ndt = DecisionTreeClassifier(\n    max_depth=4,\n    min_samples_split=20,\n    random_state=42\n)\ndt.fit(X_train, y_train)\n\nprint(f"Train acc: {dt.score(X_train, y_train):.3f}")\nprint(f"Test  acc: {dt.score(X_test, y_test):.3f}")\n\n# Hangi özellik önemli?\nimportances = pd.Series(\n    dt.feature_importances_,\n    index=X.columns\n).sort_values(ascending=False)\nprint(importances)`,
      },
      {
        tip: 'eslestir',
        soru: 'Sınıflandırma kavramlarını eşleştir:',
        cifitler: [
          { sol: 'predict()', sag: 'Sınıf etiketi döndür' },
          { sol: 'predict_proba()', sag: 'Olasılık döndür' },
          { sol: 'max_depth', sag: 'Overfitting kontrolü' },
          { sol: 'feature_importances_', sag: 'Özellik önemi' },
        ],
        aciklama: 'max_depth sınırlamak Decision Tree\'nin genelleme yapmasını sağlar. Derinlik arttıkça overfitting riski artar.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Eğitim accuracy %98, test accuracy %62.\nBu ne anlama gelir?',
        secenekler: [
          'Model çok iyi çalışıyor',
          'Overfitting — model eğitim verisini ezberliyor',
          'Underfitting — model öğrenemiyor',
          'Veri seti çok küçük',
        ],
        dogru: 1,
        aciklama: 'Eğitim-test arasındaki büyük fark overfitting\'in klasik göstergesi. Model ezberliyor, genelleme yapamıyor.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Sınıflandırma modeli eğitim akışını sırala:',
        satirlar: [
          'print(accuracy_score(y_test, y_pred))',
          'model = LogisticRegression()',
          'X_train, X_test, y_train, y_test = train_test_split(X, y)',
          'y_pred = model.predict(X_test)',
          'model.fit(X_train, y_train)',
        ],
        dogru_sira: [2, 1, 4, 3, 0],
        aciklama: 'böl → model kur → eğit → tahmin et → değerlendir.',
      },
    ],
  },
  {
    id: 'model-degerlendirme',
    baslik: 'Model Değerlendirme',
    emoji: '📐',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 40,
    konular: ['Confusion Matrix', 'Precision', 'Recall', 'ROC-AUC'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Confusion Matrix',
        aciklama: 'Accuracy tek başına yanıltıcı olabilir. Confusion matrix hangi hataları yaptığını gösterir.',
        kod: `from sklearn.metrics import confusion_matrix, classification_report\n\n# Gerçek ve tahmin edilen değerler\ny_test =  [1, 0, 1, 1, 0, 0, 1, 0, 1, 0]\ny_pred =  [1, 0, 1, 0, 0, 1, 1, 0, 0, 0]\n\ncm = confusion_matrix(y_test, y_pred)\nprint(cm)\n# [[TN  FP]\n#  [FN  TP]]\n# TN=3 FP=1\n# FN=2 TP=3\n\nprint(classification_report(y_test, y_pred))\n# precision, recall, f1 otomatik`,
      },
      {
        tip: 'eslestir',
        soru: 'Confusion matrix kavramlarını eşleştir:',
        cifitler: [
          { sol: 'True Positive (TP)', sag: 'Hasta → Hasta tahmin' },
          { sol: 'False Positive (FP)', sag: 'Sağlıklı → Hasta tahmin' },
          { sol: 'False Negative (FN)', sag: 'Hasta → Sağlıklı tahmin' },
          { sol: 'True Negative (TN)', sag: 'Sağlıklı → Sağlıklı tahmin' },
        ],
        aciklama: 'FP = alarm (yanlış pozitif), FN = kaçırma (yanlış negatif). Hangisi daha tehlikeli senaryoya göre değişir.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Kanser tespiti yapıyorsun.\nFN (hasta ama sağlıklı tahmin) ve FP (sağlıklı ama hasta tahmin) hangi metriği optimize etmelisin?',
        secenekler: [
          'Accuracy\'yi maksimize et',
          'Recall\'ı maksimize et — hiç hasta kaçırma',
          'Precision\'ı maksimize et — gereksiz alarm azalt',
          'İkisi eşit önemlidir',
        ],
        dogru: 1,
        aciklama: 'Tıbbi tanı gibi kritik durumlarda FN (hasta kaçırma) çok tehlikeli. Bu yüzden Recall önceliklidir. Precision daha az acil alarm durumlarında öncelikli.',
      },
      {
        tip: 'ogret',
        baslik: 'Precision, Recall ve ROC-AUC',
        aciklama: 'F1 Precision ve Recall\'ın harmonik ortalaması. ROC-AUC eşik bağımsız performans ölçer.',
        kod: `from sklearn.metrics import (\n    precision_score, recall_score, f1_score, roc_auc_score\n)\n\n# Precision: tahmin ettiğin pozitifler ne kadar doğru?\nprecision = precision_score(y_test, y_pred)\n# = TP / (TP + FP)\n\n# Recall (Sensitivity): gerçek pozitifleri ne kadar yakalıyorsun?\nrecall = recall_score(y_test, y_pred)\n# = TP / (TP + FN)\n\n# F1: ikisinin dengeli ortalaması\nf1 = f1_score(y_test, y_pred)\n\n# ROC-AUC: olasılık tabanlı (0.5=rastgele, 1.0=mükemmel)\nauc = roc_auc_score(y_test, y_proba)\n\nprint(f"Precision: {precision:.3f}")\nprint(f"Recall:    {recall:.3f}")\nprint(f"F1:        {f1:.3f}")\nprint(f"AUC:       {auc:.3f}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'F1 skoru Precision ve Recall\'dan neden daha iyi bir metrik olabilir?',
        secenekler: [
          'F1 her zaman daha büyük çıkar',
          'Dengesiz sınıflarda ikisini birden dengeler',
          'Hesaplanması daha kolaydır',
          'Daha yorumlanabilirdir',
        ],
        dogru: 1,
        aciklama: 'Dengesiz veri setlerinde (örn. %1 pozitif) accuracy yanıltıcı olur. F1 her ikisini dengeler ve daha anlamlı sonuç verir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Sınıflandırma değerlendirme akışı:',
        satirlar: [
          'print(roc_auc_score(y_test, y_proba))',
          'y_proba = model.predict_proba(X_test)[:, 1]',
          'y_pred = model.predict(X_test)',
          'print(classification_report(y_test, y_pred))',
        ],
        dogru_sira: [2, 3, 1, 0],
        aciklama: 'Önce etiket tahmini → classification report → olasılık tahmini → AUC hesapla.',
      },
    ],
  },
  {
    id: 'kumeleme',
    baslik: 'Kümeleme: K-Means',
    emoji: '🔵',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 35,
    konular: ['K-Means', 'Elbow', 'Silhouette', 'Unsupervised'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'K-Means Algoritması',
        aciklama: 'K-Means etiket gerekmez — unsupervised learning. Veriyi k kümeye böler. Müşteri segmentasyonu, anomali tespiti için kullanılır.',
        kod: `from sklearn.cluster import KMeans\nfrom sklearn.preprocessing import StandardScaler\nimport pandas as pd\n\n# Müşteri segmentasyonu\ndf = pd.DataFrame({'yas':[25,27,55,60,30,28], 'harcama':[200,180,800,900,210,190]})\n\n# ÖNEMLI: önce ölçekle!\nscaler = StandardScaler()\nX_sc = scaler.fit_transform(df)\n\n# 3 küme oluştur\nkm = KMeans(n_clusters=3, random_state=42, n_init=10)\nkm.fit(X_sc)\n\ndf['kume'] = km.labels_\nprint(df.groupby('kume')[['yas','harcama']].mean())`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'K-Means\'i uygulamadan önce neden ölçekleme yapmalısın?',
        secenekler: [
          'Algoritma daha hızlı çalışır',
          'Büyük ölçekli özellikler mesafe hesabını domine eder',
          'sklearn zorunlu kılıyor',
          'Küme sayısını belirler',
        ],
        dogru: 1,
        aciklama: 'K-Means Öklid mesafesi kullanır. Maaş (0-50000) ve yaş (20-60) aynı ölçekte olmadan maaş mesafeyi domine eder.',
      },
      {
        tip: 'ogret',
        baslik: 'Elbow ve Silhouette ile k Seçimi',
        aciklama: 'Doğru küme sayısını bulmak için Elbow yöntemi inertia\'yı, Silhouette skoru ise küme kalitesini ölçer.',
        kod: `from sklearn.metrics import silhouette_score\nimport matplotlib.pyplot as plt\n\ninertia = []\nsilhouette = []\nK_aralik = range(2, 10)\n\nfor k in K_aralik:\n    km = KMeans(n_clusters=k, random_state=42, n_init=10)\n    km.fit(X_sc)\n    inertia.append(km.inertia_)             # küme içi mesafe toplamı\n    silhouette.append(silhouette_score(X_sc, km.labels_))\n\n# Elbow plot\nplt.plot(K_aralik, inertia, 'o-')\nplt.xlabel('k (küme sayısı)')\nplt.ylabel('Inertia')\nplt.title('Elbow Yöntemi')\n# → "dirsek" noktası optimal k\n\n# Silhouette: 1\'e yakın = iyi ayrışmış kümeler`,
      },
      {
        tip: 'eslestir',
        soru: 'K-Means kavramlarını eşleştir:',
        cifitler: [
          { sol: 'Inertia', sag: 'Küme içi toplam mesafe' },
          { sol: 'Elbow yöntemi', sag: 'Optimal k seçimi grafiği' },
          { sol: 'Silhouette skoru', sag: 'Küme kalitesi (-1 ile 1)' },
          { sol: 'Centroid', sag: 'Küme merkezi' },
        ],
        aciklama: 'Silhouette skoru 1\'e yaklaşırsa kümeler iyi ayrışmış demek. 0\'a yakın değerler örtüşen kümeler.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'K-Means ve Lojistik Regresyon arasındaki temel fark nedir?',
        secenekler: [
          'K-Means daha hızlıdır',
          'K-Means etiket (y) gerektirmez — unsupervised learning',
          'Lojistik Regresyon kümeleme yapar',
          'K-Means sadece 2 küme bulabilir',
        ],
        dogru: 1,
        aciklama: 'K-Means unsupervised\'dir: etiket olmadan kalıpları keşfeder. Lojistik Regresyon supervised\'dir: etiketli veriyle öğrenir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'K-Means kümeleme akışını sırala:',
        satirlar: [
          'df["kume"] = km.labels_',
          'X_sc = StandardScaler().fit_transform(df)',
          'km = KMeans(n_clusters=3, random_state=42)',
          'print(silhouette_score(X_sc, km.labels_))',
          'km.fit(X_sc)',
        ],
        dogru_sira: [1, 2, 4, 0, 3],
        aciklama: 'Ölçekle → model kur → fit et → etiket ata → kaliteyi değerlendir.',
      },
    ],
  },
  {
    id: 'hipotez-testi',
    baslik: 'İstatistiksel Testler',
    emoji: '📏',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 35,
    konular: ['p-değeri', 't-test', 'Chi-square', 'Güven Aralığı'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'p-Değeri ve Hipotez Testi',
        aciklama: 'İstatistiksel testler, gözlemlediğimiz farkın şans eseri mi yoksa gerçek mi olduğunu söyler. p < 0.05 → istatistiksel anlamlı.',
        kod: `from scipy import stats\nimport numpy as np\n\n# H0: İki grubun ortalaması eşit\n# H1: Farklı\n\ngrup_a = np.random.normal(100, 15, 50)  # kontrol\ngrup_b = np.random.normal(108, 15, 50)  # deney\n\n# Bağımsız örneklem t-testi\nt_stat, p_deger = stats.ttest_ind(grup_a, grup_b)\n\nprint(f"t istatistiği: {t_stat:.3f}")\nprint(f"p-değeri:      {p_deger:.4f}")\n\nif p_deger < 0.05:\n    print("H0 reddedildi — anlamlı fark var")\nelse:\n    print("H0 reddedilemedi — fark şans eseri olabilir")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'A/B testinde p-değeri = 0.03 çıktı.\nAlpha = 0.05 kabul edilmişse ne yaparsın?',
        secenekler: [
          'H0\'ı kabul et, fark yok',
          'H0\'ı reddet, B versiyonu istatistiksel olarak daha iyi',
          'Testi tekrar et',
          'p < 0.05 olduğu için test geçersiz',
        ],
        dogru: 1,
        aciklama: 'p < alpha (0.03 < 0.05) → H0 reddedilir. Gözlemlenen fark %5 anlamlılık düzeyinde istatistiksel olarak anlamlıdır.',
      },
      {
        tip: 'ogret',
        baslik: 'Chi-square ve Güven Aralığı',
        aciklama: 'Chi-square kategorik değişkenler arasındaki ilişkiyi test eder. Güven aralığı tahminin kesinliğini gösterir.',
        kod: `# Chi-square testi — bağımsızlık\n# H0: Cinsiyet ve ürün tercihi bağımsız\nkontinjansi = [[30, 10], [15, 45]]\nchi2, p, dof, beklenen = stats.chi2_contingency(kontinjans)\nprint(f"Chi2: {chi2:.2f}, p: {p:.4f}")\n\n# Güven Aralığı (Bootstrap yöntemi)\nimport numpy as np\ndef bootstrap_mean_ci(veri, n_boot=1000, ci=95):\n    means = [np.mean(np.random.choice(veri, len(veri)))\n             for _ in range(n_boot)]\n    alt = np.percentile(means, (100-ci)/2)\n    ust = np.percentile(means, 100-(100-ci)/2)\n    return alt, ust\n\nalt, ust = bootstrap_mean_ci(grup_b)\nprint(f"%95 GA: [{alt:.2f}, {ust:.2f}]")`,
      },
      {
        tip: 'eslestir',
        soru: 'İstatistiksel test kavramlarını eşleştir:',
        cifitler: [
          { sol: 'H0 (Null hipotez)', sag: 'Fark yok varsayımı' },
          { sol: 'p < 0.05', sag: 'H0 reddedilir' },
          { sol: 'Chi-square testi', sag: 'Kategorik bağımsızlık testi' },
          { sol: '%95 güven aralığı', sag: 'Gerçek değer %95 ihtimalle bu aralıkta' },
        ],
        aciklama: 'p-değeri yanlış anlaşılır: "etki büyüklüğü" değil, null hipotezin reddi için kanıt gücüdür.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'p-değeri = 0.001 çıktı. Bu ne anlama GELMEZ?',
        secenekler: [
          'Sonuç istatistiksel olarak anlamlıdır',
          'Null hipotez reddedilir',
          'Etki büyüklüğü kesinlikle büyüktür',
          'Şans eseri gözlemlenme ihtimali çok düşüktür',
        ],
        dogru: 2,
        aciklama: 'p-değeri etki büyüklüğünü ölçmez! Küçük p, büyük örneklemde bile çok küçük farkları anlamlı gösterebilir. Effect size (Cohen\'s d gibi) ayrı hesaplanmalı.',
      },
      {
        tip: 'kod_sirala',
        soru: 'A/B test değerlendirme akışını sırala:',
        satirlar: [
          'print("Anlamlı" if p < 0.05 else "Anlamlı değil")',
          't, p = stats.ttest_ind(kontrol, deney)',
          'from scipy import stats',
          'kontrol = veri[veri.grup=="A"]["metrik"].values',
          'deney = veri[veri.grup=="B"]["metrik"].values',
        ],
        dogru_sira: [2, 3, 4, 1, 0],
        aciklama: 'import → grupları ayır → t-test → p-değerini yorumla.',
      },
    ],
  },
  {
    id: 'bias-variance',
    baslik: 'Bias-Variance Trade-off',
    emoji: '⚖️',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 40,
    konular: ['Underfitting', 'Overfitting', 'Cross-Val', 'Regularization'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Bias ve Variance Nedir?',
        aciklama: 'Bias yüksek → model çok basit (underfitting). Variance yüksek → model çok karmaşık (overfitting). İkisini dengelemek gerekir.',
        kod: `# Bias: model yeterince karmaşık değil\n# Örnek: Polinom veriye lineer model\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.preprocessing import PolynomialFeatures\n\n# Underfitting → High Bias\nlin = LinearRegression()\nlin.fit(X_train, y_train)\nprint(f"Train: {lin.score(X_train,y_train):.3f},"  \n      f" Test: {lin.score(X_test,y_test):.3f}")\n# → Train: 0.45, Test: 0.43  (her ikisi de düşük = bias)\n\n# Overfitting → High Variance\npoly10 = PolynomialFeatures(degree=10)\nX_p = poly10.fit_transform(X_train)\nmodel = LinearRegression().fit(X_p, y_train)\n# → Train: 0.99, Test: 0.31  (büyük fark = variance)`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Eğitim R²=0.95, Test R²=0.54 çıktı.\nNe yapmalısın?',
        secenekler: [
          'Modeli daha karmaşık yap',
          'Daha fazla eğitim verisi topla veya regularization ekle',
          'Test setini değiştir',
          'Hiçbir şey — model iyi',
        ],
        dogru: 1,
        aciklama: 'Büyük train-test farkı overfitting. Çözüm: daha fazla veri, regularization (L1/L2), model karmaşıklığını azaltmak.',
      },
      {
        tip: 'ogret',
        baslik: 'Cross-Validation ve Regularization',
        aciklama: 'k-Fold CV daha güvenilir performans tahminleri verir. Regularization modeli "cezalandırarak" overfitting\'i önler.',
        kod: `from sklearn.model_selection import cross_val_score\nfrom sklearn.linear_model import Ridge, Lasso\n\n# 5-Fold Cross Validation\nscores = cross_val_score(model, X, y, cv=5, scoring='r2')\nprint(f"CV R²: {scores.mean():.3f} ± {scores.std():.3f}")\n\n# Ridge (L2 ceza): ağırlıkları küçük tutar\nridge = Ridge(alpha=1.0)  # alpha arttıkça regularization güçlenir\nridge.fit(X_train, y_train)\n\n# Lasso (L1 ceza): bazı ağırlıkları tam sıfırlar → özellik seçimi\nlasso = Lasso(alpha=0.1)\nlasso.fit(X_train, y_train)\nprint("Sıfır olmayan özellikler:", (lasso.coef_ != 0).sum())`,
      },
      {
        tip: 'eslestir',
        soru: 'Overfitting çözümlerini eşleştir:',
        cifitler: [
          { sol: 'Daha fazla eğitim verisi', sag: 'Variance\'ı düşürür' },
          { sol: 'Ridge/Lasso', sag: 'Ağırlıkları cezalandırır' },
          { sol: 'max_depth azalt', sag: 'Decision Tree\'yi sınırla' },
          { sol: 'Cross-validation', sag: 'Güvenilir performans tahmini' },
        ],
        aciklama: 'Regularization en güçlü anti-overfitting araçtır. CV hem parametre seçimi hem de güvenilir değerlendirme sağlar.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Ridge ve Lasso arasındaki temel fark nedir?',
        secenekler: [
          'Ridge daha hızlıdır',
          'Lasso bazı katsayıları tam sıfıra indirir — otomatik özellik seçimi',
          'Ridge daha iyi sonuç verir',
          'Lasso sadece sınıflandırmada kullanılır',
        ],
        dogru: 1,
        aciklama: 'Lasso (L1) katsayıları tam sıfıra götürebilir → etkili özellik seçimi. Ridge (L2) ağırlıkları küçük tutar ama sıfırlamaz.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Cross-validation ile model karşılaştır:',
        satirlar: [
          'print(f"Ridge: {ridge_cv.mean():.3f}, Lasso: {lasso_cv.mean():.3f}")',
          'ridge_cv = cross_val_score(Ridge(alpha=1), X, y, cv=5)',
          'lasso_cv = cross_val_score(Lasso(alpha=0.1), X, y, cv=5)',
          'from sklearn.model_selection import cross_val_score',
        ],
        dogru_sira: [3, 1, 2, 0],
        aciklama: 'import → her model için CV → sonuçları karşılaştır.',
      },
    ],
  },
  {
    id: 'zaman-serisi',
    baslik: 'Zaman Serisi Analizi',
    emoji: '📈',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 40,
    konular: ['Trend', 'Mevsimsellik', 'Decompose', 'Tahmin'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Zaman Serisi Bileşenleri',
        aciklama: 'Zaman serisi Trend + Mevsimsellik + Gürültü\'den oluşur. Her bileşeni ayrı analiz etmek yoruma büyük katkı sağlar.',
        kod: `import pandas as pd\nimport matplotlib.pyplot as plt\nfrom statsmodels.tsa.seasonal import seasonal_decompose\n\n# Aylık satış verisi\ndf = pd.read_csv('satis.csv', parse_dates=['tarih'], index_col='tarih')\n\n# Decompose: bileşenlere ayır\nsonuc = seasonal_decompose(df['satis'], model='additive', period=12)\n\nfig, axes = plt.subplots(4, 1, figsize=(12, 8))\nsonuc.observed.plot(ax=axes[0], title='Orijinal')\nsonuc.trend.plot(ax=axes[1], title='Trend')\nsonuc.seasonal.plot(ax=axes[2], title='Mevsimsellik')\nsonuc.resid.plot(ax=axes[3], title='Artık (Gürültü)')\nplt.tight_layout()`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Bir e-ticaret sitesinde Aralık ayı satışları her yıl zirve yapıyor.\nBu hangi bileşene örnektir?',
        secenekler: ['Trend', 'Mevsimsellik', 'Gürültü', 'Artık'],
        dogru: 1,
        aciklama: 'Mevsimsellik, belirli periyotlarda (haftalık, aylık, yıllık) tekrar eden kalıplardır. Aralık zirveleri yıllık mevsimsellik.',
      },
      {
        tip: 'ogret',
        baslik: 'Hareketli Ortalama ve Tahmin',
        aciklama: 'Hareketli ortalama gürültüyü azaltır. Basit tahmin yöntemleri baseline oluşturmak için çok değerlidir.',
        kod: `# Hareketli ortalama\ndf['MA7']  = df['satis'].rolling(window=7).mean()   # 7 günlük\ndf['MA30'] = df['satis'].rolling(window=30).mean()  # 30 günlük\n\n# Yüzde değişim\ndf['degisim_yoy'] = df['satis'].pct_change(periods=365) * 100\ndf['degisim_mom'] = df['satis'].pct_change(periods=30)  * 100\n\n# Basit tahmin: önceki dönem\ndf['tahmin_naive'] = df['satis'].shift(1)  # dün = bugün tahmini\ndf['tahmin_ma7']   = df['satis'].shift(1).rolling(7).mean()\n\n# Hata metrikleri\nfrom sklearn.metrics import mean_absolute_error, mean_squared_error\nmae = mean_absolute_error(df.dropna()['satis'], df.dropna()['tahmin_ma7'])\nprint(f"MAE: {mae:.2f}")`,
      },
      {
        tip: 'eslestir',
        soru: 'Zaman serisi kavramlarını eşleştir:',
        cifitler: [
          { sol: 'Trend', sag: 'Uzun vadeli yükseliş/düşüş' },
          { sol: 'Mevsimsellik', sag: 'Düzenli tekrar eden kalıp' },
          { sol: 'rolling(7).mean()', sag: '7 günlük hareketli ortalama' },
          { sol: 'pct_change()', sag: 'Dönemsel yüzde değişim' },
        ],
        aciklama: 'rolling() zaman serisi analizinin temel aracı. Pencere büyüdükçe daha az gürültü ama daha yavaş tepki.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df["satis"].rolling(window=7).mean() için ilk 6 satır neden NaN döner?',
        secenekler: [
          'Pandas hatası',
          'İlk 7 satır için yeterli önceki gün yok',
          'rolling() sadece sayısal veride çalışır',
          'window=7 yanlış parametre',
        ],
        dogru: 1,
        aciklama: '7 günlük pencere için ilk hesaplama ancak 7. satırda yapılabilir. 1-6. satırların geçmişi yetersiz, bu yüzden NaN.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Satış verisini yükle, 30 günlük MA hesapla ve MAE hesapla:',
        satirlar: [
          'mae = mean_absolute_error(df.dropna()["satis"], df.dropna()["MA30"])',
          'df["MA30"] = df["satis"].rolling(30).mean()',
          'df = pd.read_csv("satis.csv", parse_dates=["tarih"], index_col="tarih")',
          'from sklearn.metrics import mean_absolute_error',
        ],
        dogru_sira: [3, 2, 1, 0],
        aciklama: 'import → veri yükle → hareketli ortalama → hata hesapla.',
      },
    ],
  },
  {
    id: 'veri-pipeline',
    baslik: 'sklearn Pipeline',
    emoji: '🔧',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 45,
    konular: ['Pipeline', 'ColumnTransformer', 'GridSearch', 'Production'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Pipeline Neden Gerekli?',
        aciklama: "Pipeline preprocessing ve modeli tek bir nesneye bağlar. Data leakage'ı önler, kodu temizler, production'a taşıyı kolaylaştırır.",
        kod: `from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n\n# Pipeline olmadan → data leakage riski:\nscaler = StandardScaler()\nX_train_sc = scaler.fit_transform(X_train)  # ✅\nX_test_sc  = scaler.transform(X_test)       # ✅ ama elle yapıyorsun\n\n# Pipeline ile → otomatik, güvenli:\npipe = Pipeline([\n    ('scaler', StandardScaler()),\n    ('model', LogisticRegression())\n])\n\npipe.fit(X_train, y_train)          # sadece X_train'e fit\ny_pred = pipe.predict(X_test)       # otomatik transform + predict\nprint(pipe.score(X_test, y_test))`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Pipeline\'ın en önemli avantajı nedir?',
        secenekler: [
          'Kodun kısalması',
          'Data leakage\'ı önler — fit() sadece eğitim verisini görür',
          'Daha hızlı çalışır',
          'Daha fazla algoritma destekler',
        ],
        dogru: 1,
        aciklama: 'Pipeline cross-validation sırasında her fold için scaler\'ı sadece eğitim parçasına fit eder. Elle yapınca bu hatayı kolayca atlarsın.',
      },
      {
        tip: 'ogret',
        baslik: 'ColumnTransformer ile Karışık Veri',
        aciklama: 'Gerçek veri hem sayısal hem kategorik içerir. ColumnTransformer her sütun tipine farklı işlem uygular.',
        kod: `from sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder, StandardScaler\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.pipeline import Pipeline\n\nsayisal = ['yas', 'maas', 'hizmet_yili']\nkategorik = ['sehir', 'departman']\n\n# Sayısal: impute + scale\nsayisal_pipe = Pipeline([\n    ('imputer', SimpleImputer(strategy='median')),\n    ('scaler', StandardScaler())\n])\n\n# Kategorik: impute + encode\nkategorik_pipe = Pipeline([\n    ('imputer', SimpleImputer(strategy='most_frequent')),\n    ('encoder', OneHotEncoder(handle_unknown='ignore'))\n])\n\npreprocessor = ColumnTransformer([\n    ('num', sayisal_pipe, sayisal),\n    ('cat', kategorik_pipe, kategorik)\n])\n\nfull_pipe = Pipeline([\n    ('prep', preprocessor),\n    ('model', LogisticRegression())\n])\n\nfull_pipe.fit(X_train, y_train)`,
      },
      {
        tip: 'eslestir',
        soru: 'Pipeline bileşenlerini eşleştir:',
        cifitler: [
          { sol: 'SimpleImputer', sag: 'Eksik değerleri doldur' },
          { sol: 'StandardScaler', sag: 'Sayısal ölçekleme' },
          { sol: 'OneHotEncoder', sag: 'Kategorik encoding' },
          { sol: 'ColumnTransformer', sag: 'Sütuna göre farklı işlem' },
        ],
        aciklama: 'ColumnTransformer + Pipeline kombinasyonu production-ready ML kodu için standarttır.',
      },
      {
        tip: 'coktan_secmeli',
        soru: 'GridSearchCV ile Pipeline kullanınca ne elde edersin?',
        secenekler: [
          'Sadece hız',
          'Her CV fold\'u için güvenli preprocessing + hiperparametre optimizasyonu',
          'Daha az kod',
          'Daha iyi görselleştirme',
        ],
        dogru: 1,
        aciklama: 'GridSearchCV + Pipeline kombinasyonu: her fold\'da preprocessing doğru şekilde uygulanır ve hiperparametreler güvenilir şekilde optimize edilir.',
      },
      {
        tip: 'kod_sirala',
        soru: 'GridSearchCV ile Pipeline parametre araması yap:',
        satirlar: [
          'print(gs.best_params_, gs.best_score_)',
          'param_grid = {"model__C": [0.01, 0.1, 1, 10]}',
          'gs = GridSearchCV(pipe, param_grid, cv=5, scoring="f1")',
          'gs.fit(X_train, y_train)',
          'from sklearn.model_selection import GridSearchCV',
        ],
        dogru_sira: [4, 1, 2, 3, 0],
        aciklama: 'import → param grid tanımla → GridSearchCV oluştur → fit → sonuçları gör.',
      },
    ],
  },
];
