export const dersler = [
  {
    id: 'python-temelleri',
    baslik: 'Python Temelleri',
    emoji: '🐍',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 20,
    konular: ['Değişkenler', 'Listeler', 'Döngüler'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Değişkenler ve Veri Tipleri',
        aciklama: "Python'da değişken tanımlamak için tür belirtmene gerek yok.",
        kod: `# Sayısal\nyas = 28\nmaas = 8500.50\n\n# Metin\nisim = "Ali"\n\n# Mantıksal\naktif = True\n\nprint(type(yas))    # int\nprint(type(isim))   # str\nprint(type(aktif))  # bool`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'x = 10\ny = 3\nprint(x // y)',
        secenekler: ['3', '3.33', '1', '30'],
        dogru: 0,
        aciklama: '// tam bölme yapar, ondalık kısmı atar. 10 // 3 = 3.',
      },
      {
        tip: 'bosluk_doldur',
        once: 'isim = ',
        bosluk: '"Sıfır Gecikme"',
        sonra: '\nprint(type(isim))  # str',
        secenekler: ['"Sıfır Gecikme"', '42', 'True', '[1,2,3]'],
        dogru: 0,
        aciklama: 'Tırnak içindeki değerler string tipindedir.',
      },
      {
        tip: 'ogret',
        baslik: 'Listeler',
        aciklama: 'Liste, birden fazla değeri sıralı tutan yapı.',
        kod: `sayilar = [3, 1, 4, 1, 5]\nisimler = ["Ali", "Ayşe"]\n\nprint(isimler[0])   # Ali\nprint(isimler[-1])  # Ayşe\nprint(len(sayilar)) # 5\nsayilar.sort()\nprint(sayilar)      # [1,1,3,4,5]`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'liste = [10, 20, 30, 40, 50]\nprint(liste[-2])',
        secenekler: ['20', '40', '50', 'Hata'],
        dogru: 1,
        aciklama: 'Negatif index sondan başlar. -2 sondan ikinci eleman: 40.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Liste oluştur, eleman ekle, uzunluğunu yazdır:',
        satirlar: [
          'print(len(meyveler))',
          'meyveler = ["elma", "armut"]',
          'meyveler.append("kiraz")',
        ],
        dogru_sira: [1, 2, 0],
        aciklama: 'Önce listele tanımla, sonra ekle, en son uzunluğu yazdır.',
      },
    ],
  },
  {
    id: 'donguler-fonksiyonlar',
    baslik: 'Döngüler & Fonksiyonlar',
    emoji: '🔄',
    renk: '#7F77DD',
    bg: '#EEEDFE',
    xp: 25,
    konular: ['for', 'while', 'def', 'return'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'for Döngüsü',
        aciklama: 'for döngüsü bir liste veya aralık üzerinde sırayla işlem yapar.',
        kod: `meyveler = ["elma", "armut", "kiraz"]\nfor meyve in meyveler:\n    print(meyve)\n\nfor i in range(5):\n    print(i, end=" ")  # 0 1 2 3 4\n\nfor i, m in enumerate(meyveler):\n    print(f"{i}: {m}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'toplam = 0\nfor i in range(1, 5):\n    toplam += i\nprint(toplam)',
        secenekler: ['10', '15', '4', '6'],
        dogru: 0,
        aciklama: 'range(1,5) → 1,2,3,4. Toplam: 1+2+3+4 = 10.',
      },
      {
        tip: 'bosluk_doldur',
        once: 'for i in ',
        bosluk: 'range(3)',
        sonra: ':\n    print(i)  # 0, 1, 2',
        secenekler: ['range(3)', 'list(3)', 'loop(3)', 'iter(3)'],
        dogru: 0,
        aciklama: "range(n) 0'dan n-1'e kadar sayılar üretir.",
      },
      {
        tip: 'ogret',
        baslik: 'Fonksiyonlar',
        aciklama: 'def ile tanımlanır, return ile değer döndürür.',
        kod: `def selam(isim):\n    return f"Merhaba, {isim}!"\n\nprint(selam("Ali"))   # Merhaba, Ali!\n\ndef kare(sayi, kuvvet=2):\n    return sayi ** kuvvet\n\nprint(kare(3))    # 9\nprint(kare(3, 3)) # 27`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'def topla(a, b=10):\n    return a + b\n\nprint(topla(5))',
        secenekler: ['5', '10', '15', 'Hata'],
        dogru: 2,
        aciklama: 'b verilmediğinde varsayılan 10 kullanılır. 5+10=15.',
      },
      {
        tip: 'kod_sirala',
        soru: 'Faktöriyel hesaplayan fonksiyon yaz:',
        satirlar: [
          'return sonuc',
          'def faktoriyel(n):',
          'sonuc = 1',
          'for i in range(1, n+1):',
          '    sonuc *= i',
        ],
        dogru_sira: [1, 2, 3, 4, 0],
        aciklama: 'def → değişken → döngü → çarp → return sırası doğru.',
      },
    ],
  },
  {
    id: 'numpy',
    baslik: 'NumPy Temelleri',
    emoji: '🔢',
    renk: '#e8a04a',
    bg: '#FAEEDA',
    xp: 30,
    konular: ['Array', 'Matris', 'İstatistik'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'NumPy Array',
        aciklama: "NumPy, sayısal hesaplama için temel kütüphane. Array listeden çok hızlı.",
        kod: `import numpy as np\n\na = np.array([1, 2, 3, 4, 5])\nprint(a.shape)  # (5,)\nprint(a * 2)    # [2 4 6 8 10]\nprint(a + 10)   # [11 12 13 14 15]\n\nnp.zeros(5)        # [0. 0. 0. 0. 0.]\nnp.arange(0,10,2)  # [0 2 4 6 8]`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'a = np.array([2, 4, 6, 8])\nprint(a.mean())',
        secenekler: ['4.0', '5.0', '20', '24'],
        dogru: 1,
        aciklama: 'Ortalama = (2+4+6+8)/4 = 20/4 = 5.0',
      },
      {
        tip: 'bosluk_doldur',
        once: 'a = np.',
        bosluk: 'zeros',
        sonra: '(4)\nprint(a)  # [0. 0. 0. 0.]',
        secenekler: ['zeros', 'empty', 'none', 'null'],
        dogru: 0,
        aciklama: 'np.zeros(n) sıfırlardan oluşan array oluşturur.',
      },
      {
        tip: 'ogret',
        baslik: 'Matris ve İstatistik',
        aciklama: '2 boyutlu array matristir.',
        kod: `M = np.array([[1,2,3],[4,5,6],[7,8,9]])\n\nprint(M.shape)       # (3,3)\nprint(M.sum())       # 45\nprint(M.sum(axis=0)) # sütun toplamları\nprint(M.sum(axis=1)) # satır toplamları\n\nveri = np.random.normal(0, 1, 1000)\nprint(veri.mean())   # ~0\nprint(veri.std())    # ~1`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'M = np.array([[1,2],[3,4]])\nprint(M.sum(axis=1))',
        secenekler: ['[4, 6]', '[3, 7]', '[1,2,3,4]', '[10]'],
        dogru: 1,
        aciklama: 'axis=1 satır toplamları: [1+2, 3+4] = [3, 7]',
      },
      {
        tip: 'kod_sirala',
        soru: 'NumPy ile array oluştur ve karesini al:',
        satirlar: [
          'print(a ** 2)',
          'import numpy as np',
          'a = np.zeros(5)',
        ],
        dogru_sira: [1, 2, 0],
        aciklama: 'import → array oluştur → işlem yap.',
      },
    ],
  },
  {
    id: 'pandas',
    baslik: 'Pandas ile Veri Analizi',
    emoji: '🐼',
    renk: '#1D9E75',
    bg: '#E1F5EE',
    xp: 35,
    konular: ['DataFrame', 'Filtreleme', 'groupby'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'DataFrame Oluşturma',
        aciklama: "DataFrame, pandas'ın temel yapısı. Tablo gibi düşün.",
        kod: `import pandas as pd\n\ndf = pd.DataFrame({\n    'isim': ['Ali','Ayşe','Mehmet'],\n    'yas':  [28, 34, 25],\n    'sehir': ['İzmir','İstanbul','Ankara'],\n    'maas': [8500, 12000, 7200]\n})\n\nprint(df.shape)    # (3, 4)\nprint(df.columns)  # isim, yas, sehir, maas\nprint(df.head(2))  # ilk 2 satır`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df.shape neyi döndürür?',
        secenekler: [
          '(sütun, satır)',
          '(satır, sütun)',
          'Satır sayısı',
          'Sütun sayısı',
        ],
        dogru: 1,
        aciklama: 'df.shape her zaman (satır, sütun) formatında döner.',
      },
      {
        tip: 'bosluk_doldur',
        once: "izmir = df[df['sehir'] == ",
        bosluk: "'İzmir'",
        sonra: ']',
        secenekler: ["'İzmir'", "'Ankara'", 'df.sehir', 'sehir'],
        dogru: 0,
        aciklama: "Boolean filtreleme: df[koşul] sadece koşulu sağlayan satırları döndürür.",
      },
      {
        tip: 'ogret',
        baslik: 'Gruplama ve Özet',
        aciklama: 'groupby ile verileri gruplara böl.',
        kod: `ozet = df.groupby('sehir').agg(\n    kisi=('isim','count'),\n    ort_maas=('maas','mean')\n).reset_index()\n\nprint(ozet)\nprint(df['maas'].describe())`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'df.groupby("sehir")["maas"].mean() ne yapar?',
        secenekler: [
          'Tüm maaşların ortalaması',
          'Kişi sayısını sayar',
          'Her şehir için ortalama maaş',
          'Maaşa göre sıralama',
        ],
        dogru: 2,
        aciklama: 'groupby şehre göre gruplar, mean() her grubun ortalamasını alır.',
      },
      {
        tip: 'kod_sirala',
        soru: 'DataFrame oluştur ve filtrele:',
        satirlar: [
          'print(izmir)',
          'import pandas as pd',
          "df = pd.DataFrame({'sehir':['İzmir','Ankara'],'maas':[8000,7000]})",
          "izmir = df[df['sehir']=='İzmir']",
        ],
        dogru_sira: [1, 2, 3, 0],
        aciklama: 'import → DataFrame → filtrele → yazdır.',
      },
    ],
  },
  {
    id: 'istatistik-ml',
    baslik: 'İstatistik & ML Giriş',
    emoji: '🤖',
    renk: '#E24B4A',
    bg: '#FCEBEB',
    xp: 40,
    konular: ['Dağılım', 'Train/Test', 'Model', 'R²'],
    adimlar: [
      {
        tip: 'ogret',
        baslik: 'Temel İstatistik',
        aciklama: 'Veri analizi istatistikle başlar.',
        kod: `import numpy as np\n\nveri = [23,25,28,22,31,27,24]\n\nprint(f"Ortalama: {np.mean(veri):.2f}")\nprint(f"Medyan:   {np.median(veri):.2f}")\nprint(f"Std:      {np.std(veri):.2f}")\nprint(f"Min/Max:  {min(veri)} / {max(veri)}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: '[1, 2, 3, 100] listesi için ortalama 26.5, medyan 2.5.\nAykırı değer varken hangisi daha güvenilir?',
        secenekler: ['Ortalama', 'Medyan', 'İkisi eşit', 'Standart sapma'],
        dogru: 1,
        aciklama: 'Aykırı değer (100) ortalamayı çok etkiler. Medyan daha sağlamdır.',
      },
      {
        tip: 'bosluk_doldur',
        once: 'from sklearn.model_selection import ',
        bosluk: 'train_test_split',
        sonra: '\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)',
        secenekler: ['train_test_split', 'split_data', 'divide_set', 'cross_val'],
        dogru: 0,
        aciklama: 'train_test_split veriyi eğitim ve test setine böler.',
      },
      {
        tip: 'ogret',
        baslik: 'İlk ML Modeli',
        aciklama: 'sklearn ile model kurmak 3 adım: fit → predict → score.',
        kod: `from sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nX = np.random.rand(100,1)*10\ny = 2.5*X.ravel() + np.random.randn(100)*2\n\nX_train,X_test,y_train,y_test = train_test_split(\n    X, y, test_size=0.2\n)\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nprint(f"R²: {model.score(X_test,y_test):.4f}")`,
      },
      {
        tip: 'coktan_secmeli',
        soru: 'Bir modelin R² skoru 0.92 çıktı. Bu ne anlama gelir?',
        secenekler: [
          'Model %8 doğru tahmin yapıyor',
          "Hedef değişkenin varyansının %92'si açıklanıyor",
          'Test hatası %92',
          'Model 0.92 hata yapıyor',
        ],
        dogru: 1,
        aciklama: "R² modelin bağımlı değişkeni ne kadar açıkladığını gösterir. 0.92 → çok iyi.",
      },
      {
        tip: 'kod_sirala',
        soru: 'Doğru ML akışını sırala:',
        satirlar: [
          'print(f"R²: {model.score(X_test,y_test):.3f}")',
          'model = LinearRegression()',
          'X_train,X_test,y_train,y_test = train_test_split(X,y)',
          'model.fit(X_train, y_train)',
          'y_pred = model.predict(X_test)',
        ],
        dogru_sira: [2, 1, 3, 4, 0],
        aciklama: 'böl → model → eğit → tahmin → değerlendir.',
      },
    ],
  },
];
