export const sorular = [
  {
    id: 1,
    kategori: 'SQL',
    soru: 'Bir tabloda aynı müşterinin birden fazla siparişi var. Her müşterinin toplam sipariş sayısını bulmak için hangi sorgu doğrudur?',
    secenekler: [
      'SELECT customer_id, SUM(*) FROM orders GROUP BY customer_id',
      'SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id',
      'SELECT customer_id, COUNT(*) FROM orders ORDER BY customer_id',
      'SELECT customer_id, TOTAL(*) FROM orders GROUP BY customer_id',
    ],
    dogru: 1,
    aciklama: 'COUNT(*) satır sayısını verir. SUM() sayısal değerleri toplar, TOTAL() diye bir fonksiyon yoktur. GROUP BY olmadan COUNT tüm tabloyu sayar.',
  },
  {
    id: 2,
    kategori: 'İstatistik',
    soru: 'A/B testinde p-değeri 0.03 çıktı ve eşiğin 0.05 olarak belirlendi. Bu ne anlama gelir?',
    secenekler: [
      'Fark rastlantısal olabilir, sonuç anlamlı değil',
      'Fark istatistiksel olarak anlamlı, H₀ reddedilir',
      'B varyantı kesinlikle daha iyi',
      'Örneklem büyüklüğü yetersiz',
    ],
    dogru: 1,
    aciklama: 'p < 0.05 olduğunda H₀ (iki grup arasında fark yok) hipotezi reddedilir. Fark istatistiksel olarak anlamlıdır. Ancak "anlamlı" pratik önemi garanti etmez — etki büyüklüğüne de bakılmalı.',
  },
  {
    id: 3,
    kategori: 'Python',
    soru: "pandas'ta bir DataFrame'deki eksik değerlerin sayısını sütun bazında bulmak için hangi kod kullanılır?",
    secenekler: [
      'df.count_null()',
      'df.missing().sum()',
      'df.isnull().sum()',
      'df.na().count()',
    ],
    dogru: 2,
    aciklama: 'isnull() her hücre için True/False döner. sum() üzerine uygulandığında True=1 sayılarak sütun başına eksik değer sayısı bulunur.',
  },
  {
    id: 4,
    kategori: 'SQL',
    soru: 'WHERE ve HAVING arasındaki temel fark nedir?',
    secenekler: [
      'WHERE daha hızlıdır, HAVING daha yavaştır',
      'WHERE satırları filtreler, HAVING grupları filtreler',
      'HAVING sadece COUNT ile kullanılır',
      'İkisi aynı işi yapar, WHERE daha modern syntax\'tır',
    ],
    dogru: 1,
    aciklama: 'WHERE, GROUP BY\'dan önce çalışır ve satır düzeyinde filtreler. HAVING, gruplama sonrası aggregate değerleri filtreler. Örneğin toplam satışı 1000\'in üzerinde olan grupları bulmak için HAVING kullanılır.',
  },
  {
    id: 5,
    kategori: 'ML',
    soru: 'Overfitting\'i azaltmak için hangisi doğrudan etkili değildir?',
    secenekler: [
      'Daha fazla eğitim verisi eklemek',
      'Regularization (L1/L2) uygulamak',
      'Modeli daha karmaşık hale getirmek',
      'Dropout kullanmak',
    ],
    dogru: 2,
    aciklama: 'Modeli daha karmaşık yapmak overfitting\'i azaltmaz, tam tersine artırır. Daha fazla veri, regularization ve dropout overfitting\'i azaltan yöntemlerdir.',
  },
  {
    id: 6,
    kategori: 'İstatistik',
    soru: 'Standart sapma ile standart hata arasındaki temel fark nedir?',
    secenekler: [
      'Standart hata her zaman daha büyüktür',
      'Standart sapma veri yayılımını, standart hata örneklem ortalamasının kesinliğini ölçer',
      'Standart hata sadece normal dağılımda kullanılır',
      'İkisi aynı şeydir, farklı terminoloji',
    ],
    dogru: 1,
    aciklama: 'Standart sapma bireysel veri noktalarının ortalamadan ne kadar saptığını gösterir. Standart hata ise örneklem ortalamasının gerçek popülasyon ortalamasından ne kadar sapabileceğini ölçer. SE = SD / √n formülüyle hesaplanır.',
  },
  {
    id: 7,
    kategori: 'SQL',
    soru: 'INNER JOIN ile LEFT JOIN farkını en iyi hangisi açıklar?',
    secenekler: [
      'INNER JOIN daha hızlıdır',
      'LEFT JOIN sol tablonun tüm satırlarını, INNER JOIN yalnızca eşleşen satırları getirir',
      'LEFT JOIN her zaman daha fazla sütun döner',
      'INNER JOIN NULL değerleri filtreler, LEFT JOIN tutmaz',
    ],
    dogru: 1,
    aciklama: 'INNER JOIN yalnızca her iki tabloda eşleşme olan satırları getirir. LEFT JOIN sol tablonun tüm satırlarını getirir; sağ tabloda eşleşme yoksa NULL döner. Hiç sipariş vermemiş müşterileri bulmak için LEFT JOIN gerekir.',
  },
  {
    id: 8,
    kategori: 'Python',
    soru: "pandas'ta df.groupby('kategori')['fiyat'].mean() ne döner?",
    secenekler: [
      'Her kategorinin toplam fiyatı',
      'Her kategorinin ortalama fiyatı, Series olarak',
      'Tüm tablonun ortalama fiyatı',
      'Her kategorideki satır sayısı',
    ],
    dogru: 1,
    aciklama: 'groupby() + mean() kombinasyonu her grup için belirtilen sütunun ortalamasını hesaplar. Sonuç, index\'i kategori adları olan bir pandas Series\'dir.',
  },
  {
    id: 9,
    kategori: 'ML',
    soru: 'Bias-variance trade-off\'ta yüksek bias ne anlama gelir?',
    secenekler: [
      'Model eğitim verisine aşırı uymuş (overfitting)',
      'Model çok basit, veriyi yeterince öğrenememiş (underfitting)',
      'Model gürültüye duyarlı',
      'Örneklem büyüklüğü yetersiz',
    ],
    dogru: 1,
    aciklama: 'Yüksek bias underfitting\'e işaret eder — model eğitim verisinde bile düşük performans gösterir. Yüksek variance ise overfitting\'dir: eğitimde iyi, test\'te kötü. İdeal model ikisini dengeler.',
  },
  {
    id: 10,
    kategori: 'SQL',
    soru: 'ROW_NUMBER(), RANK() ve DENSE_RANK() fonksiyonlarından hangisi eşit değerlerde boşluk bırakmaz?',
    secenekler: [
      'ROW_NUMBER()',
      'RANK()',
      'DENSE_RANK()',
      'Üçü de boşluk bırakmaz',
    ],
    dogru: 2,
    aciklama: 'RANK() eşit değerlere aynı sıra verir ve sonraki sırayı atlar (1,1,3). DENSE_RANK() eşit değerlere aynı sıra verir ama atlamaz (1,1,2). ROW_NUMBER() eşit değere bile farklı numara verir (1,2,3).',
  },
  {
    id: 11,
    kategori: 'Python',
    soru: "df[df['yas'] > 30] ifadesi ne yapar?",
    secenekler: [
      "yas sütununda 30'dan büyük değerleri siler",
      "yas değeri 30'dan büyük olan satırları filtreler",
      "yas sütununun 30. satırını getirir",
      "yas sütununu 30 ile çarpar",
    ],
    dogru: 1,
    aciklama: "Boolean indexing: df['yas'] > 30 her satır için True/False üretir. Bu mask DataFrame'e uygulandığında yalnızca True olan satırlar döner. pandas'ın en temel filtreleme yöntemidir.",
  },
  {
    id: 12,
    kategori: 'İstatistik',
    soru: 'Korelasyon katsayısı -0.85 olan iki değişken için ne söylenebilir?',
    secenekler: [
      'Biri artarken diğeri azalır ve ilişki güçlüdür',
      'İki değişken arasında nedensellik vardır',
      'İlişki zayıftır ve yönü belirsizdir',
      'Biri artarken diğeri de artar',
    ],
    dogru: 0,
    aciklama: '-0.85, güçlü negatif korelasyona işaret eder: biri artarken diğeri azalır. Ancak korelasyon nedensellik (causation) kanıtlamaz — üçüncü bir değişken her ikisini de etkiliyor olabilir.',
  },
  {
    id: 13,
    kategori: 'SQL',
    soru: 'Aşağıdaki sorgulardan hangisi sözdizimi olarak hatalıdır?',
    secenekler: [
      'SELECT name, COUNT(*) FROM orders GROUP BY name HAVING COUNT(*) > 5',
      'SELECT name, COUNT(*) FROM orders WHERE COUNT(*) > 5 GROUP BY name',
      'SELECT name FROM orders WHERE name IS NOT NULL ORDER BY name',
      'SELECT DISTINCT name FROM orders',
    ],
    dogru: 1,
    aciklama: "WHERE içinde aggregate fonksiyon (COUNT, SUM vb.) kullanılamaz. WHERE gruplamadan önce çalışır, henüz COUNT hesaplanmamıştır. Aggregate filtrelemesi için HAVING kullanılır.",
  },
  {
    id: 14,
    kategori: 'ML',
    soru: 'Precision ve Recall arasındaki trade-off\'u en iyi ifade eden seçenek hangisidir?',
    secenekler: [
      'Precision artarken Recall her zaman sabit kalır',
      'Eşik değeri yükseltilince Precision artar, Recall düşer',
      'Eşik değeri yükseltilince her ikisi de artar',
      'İkisi aynı metriği farklı adlandırır',
    ],
    dogru: 1,
    aciklama: 'Sınıflandırma eşiğini yükseltmek modeli daha seçici yapar: daha az pozitif tahmin, daha yüksek Precision. Ama gerçek pozitiflerin bir kısmı kaçırılır, Recall düşer. F1-score bu ikisini dengeleyen harmonik ortalamadır.',
  },
  {
    id: 15,
    kategori: 'Python',
    soru: "pandas'ta merge() ile join() arasındaki temel fark nedir?",
    secenekler: [
      'join() her zaman daha hızlıdır',
      'merge() herhangi bir sütuna göre birleştirir, join() varsayılan olarak index\'e göre birleştirir',
      'merge() sadece SQL benzeri JOIN yapar',
      'join() birden fazla DataFrame desteklemez',
    ],
    dogru: 1,
    aciklama: 'merge() herhangi bir sütun(lar) üzerinden birleştirme yapar ve SQL JOIN mantığına benzer. join() ise varsayılan olarak DataFrame index\'ini kullanır. İkisi de benzer işleri yapabilir ama merge() daha esnektir.',
  },
  {
    id: 16,
    kategori: 'İstatistik',
    soru: 'Merkezi Limit Teoremi ne söyler?',
    secenekler: [
      'Her veri seti normal dağılımlıdır',
      'Yeterince büyük örneklemlerde, örneklem ortalamaları normal dağılıma yaklaşır',
      'Ortalama her zaman medyana eşittir',
      'Büyük örneklemlerde standart sapma sıfıra yaklaşır',
    ],
    dogru: 1,
    aciklama: 'Merkezi Limit Teoremi: orijinal dağılım ne olursa olsun, yeterince büyük bağımsız örneklemlerin ortalamaları normal dağılıma yaklaşır. Bu teorem istatistiksel testlerin çoğunun temelini oluşturur.',
  },
  {
    id: 17,
    kategori: 'SQL',
    soru: 'CTE (Common Table Expression) kullanmanın temel avantajı nedir?',
    secenekler: [
      'CTE\'ler her zaman subquery\'den daha hızlıdır',
      'Karmaşık sorguları okunabilir parçalara böler ve tekrar kullanılabilir',
      'CTE\'ler geçici tablo oluşturur ve diskte saklanır',
      'Sadece PostgreSQL destekler',
    ],
    dogru: 1,
    aciklama: 'WITH ifadesiyle tanımlanan CTE\'ler sorguyu mantıksal adımlara böler, okunabilirliği artırır. Aynı alt sorguya birden fazla kez başvurulabilir. Performans farkı veritabanına göre değişir; okunabilirlik en belirgin kazanımdır.',
  },
  {
    id: 18,
    kategori: 'Python',
    soru: "df['tarih'] = pd.to_datetime(df['tarih']) satırı ne işe yarar?",
    secenekler: [
      'tarih sütununu bugünün tarihiyle doldurur',
      'tarih sütununu string\'den datetime tipine dönüştürür',
      'tarih sütununu siler ve yeniden oluşturur',
      'Tarihleri alfabetik sıraya koyar',
    ],
    dogru: 1,
    aciklama: 'pd.to_datetime() string veya sayısal tarih değerlerini pandas datetime64 tipine çevirir. Bu dönüşüm yapılmadan .dt.month, .dt.year gibi tarih özellikleri kullanılamaz ve tarih bazlı filtreleme çalışmaz.',
  },
  {
    id: 19,
    kategori: 'ML',
    soru: 'K-Means algoritmasında K değerini seçmek için yaygın kullanılan yöntem hangisidir?',
    secenekler: [
      'Her zaman K=3 kullanılır',
      'Elbow method — inertia\'nın K\'ya göre grafiği',
      'K değeri verinin satır sayısına eşit seçilir',
      'Grid search ile otomatik bulunur',
    ],
    dogru: 1,
    aciklama: 'Elbow method\'da farklı K değerleri için inertia (küme içi kareler toplamı) hesaplanır. Grafikte "dirsek" gibi kırılan noktadaki K optimal seçimdir. Silhouette score da başka bir yaygın yöntemdir.',
  },
  {
    id: 20,
    kategori: 'SQL',
    soru: 'NULL değerlerle ilgili hangisi doğrudur?',
    secenekler: [
      "NULL = NULL ifadesi TRUE döner",
      "NULL karşılaştırmalarında IS NULL veya IS NOT NULL kullanılmalıdır",
      "NULL her zaman 0'a eşittir",
      "NULL'ı toplamak her zaman NULL verir",
    ],
    dogru: 1,
    aciklama: "NULL bilinmeyen değeri temsil eder. NULL = NULL TRUE değil, NULL (bilinmeyen) döner. Karşılaştırma için IS NULL / IS NOT NULL kullanılır. SUM() NULL'ları yok sayar ama tüm değerler NULL ise NULL döner.",
  },
  {
    id: 21,
    kategori: 'İstatistik',
    soru: 'Histogram ile bar chart arasındaki temel fark nedir?',
    secenekler: [
      'Histogram renkli, bar chart renksizdir',
      'Histogram sürekli sayısal veriyi, bar chart kategorik veriyi gösterir',
      'Bar chart her zaman dikey, histogram yatay olur',
      'İkisi aynı grafiğin farklı adlarıdır',
    ],
    dogru: 1,
    aciklama: 'Histogram sürekli sayısal dağılımı aralıklara (bin) bölerek gösterir; çubuklar bitişiktir. Bar chart kategorik değişkenlerin frekansını veya değerini karşılaştırır; çubuklar arasında boşluk vardır.',
  },
  {
    id: 22,
    kategori: 'Python',
    soru: "df.describe() metodu hangi istatistikleri göstermez?",
    secenekler: [
      'Ortalama (mean)',
      'Standart sapma (std)',
      'Mod (en sık tekrar eden değer)',
      'Medyan (%50)',
    ],
    dogru: 2,
    aciklama: "describe() sayısal sütunlar için count, mean, std, min, %25, %50, %75 ve max değerlerini gösterir. Mod (mode) bu çıktıya dahil değildir; df['sütun'].mode() ile ayrıca hesaplanabilir.",
  },
  {
    id: 23,
    kategori: 'ML',
    soru: 'Random Forest, karar ağaçlarına kıyasla genellikle neden daha iyi performans gösterir?',
    secenekler: [
      'Daha az hesaplama gücü gerektirir',
      'Birden fazla ağacın tahminlerini birleştirerek varyansı azaltır',
      'Her zaman daha hızlı eğitilir',
      'Sadece sınıflandırma problemlerinde çalışır',
    ],
    dogru: 1,
    aciklama: "Random Forest, bagging yöntemiyle veri alt kümelerinde eğitilen çok sayıda ağacın tahminlerini ortalar (regresyon) veya çoğunluk oyuyla (sınıflandırma) birleştirir. Bu ensemble yaklaşımı tek ağacın yüksek varyansını azaltır.",
  },
  {
    id: 24,
    kategori: 'SQL',
    soru: "Bir tabloda running total (kümülatif toplam) hesaplamak için hangi yaklaşım kullanılır?",
    secenekler: [
      'GROUP BY + SUM()',
      'SUM() OVER (ORDER BY tarih)',
      'CUMSUM() fonksiyonu',
      'TOTAL() + ORDER BY',
    ],
    dogru: 1,
    aciklama: 'Window function olan SUM() OVER (ORDER BY ...) her satır için o satıra kadar olan toplamı hesaplar. GROUP BY toplamayı tek değere düşürür, window function ise her satırı koruyarak üzerine hesaplama yapar.',
  },
  {
    id: 25,
    kategori: 'İstatistik',
    soru: 'Box plot\'ta IQR (Interquartile Range) neyi temsil eder?',
    secenekler: [
      'Minimum ile maksimum arasındaki fark',
      '%25 ile %75 persantil arasındaki fark (orta %50\'nin yayılımı)',
      'Medyan ile ortalama arasındaki fark',
      'Standart sapmanın 2 katı',
    ],
    dogru: 1,
    aciklama: "IQR = Q3 - Q1 (%75 - %25). Verinin orta %50'sinin yayılımını gösterir ve uç değerlere (outlier) karşı dayanıklıdır. Box plot'ta aykırı değer tespitinde 1.5×IQR kuralı yaygın olarak kullanılır.",
  },
  {
    id: 26,
    kategori: 'Python',
    soru: "df.drop_duplicates() ve df.drop_duplicates(subset=['email']) arasındaki fark nedir?",
    secenekler: [
      'İkisi tamamen aynı işi yapar',
      "İlki tüm sütunlar aynıysa siler, ikincisi yalnızca 'email' aynıysa siler",
      "İlki hızlı, ikincisi yavaş çalışır",
      "subset parametresi yalnızca sayısal sütunlarda çalışır",
    ],
    dogru: 1,
    aciklama: "drop_duplicates() varsayılan olarak tüm sütunların aynı olduğu satırları siler. subset parametresiyle sadece belirtilen sütun(lar)a göre tekrar eden satırlar silinir. Aynı email'i olan farklı kullanıcıları temizlemek için subset kullanılır.",
  },
  {
    id: 27,
    kategori: 'ML',
    soru: 'Gradient descent\'te learning rate çok büyük seçilirse ne olur?',
    secenekler: [
      'Model daha hızlı yakınsar',
      'Optimizasyon salınım yapar veya minimize edemez',
      'Overfitting artar',
      'Hiçbir etkisi olmaz',
    ],
    dogru: 1,
    aciklama: 'Büyük learning rate adım boyutunu artırır. Bu minimum etrafında salınıma veya loss\'un artmasına yol açabilir. Çok küçük learning rate ise yavaş öğrenmeye ve local minimum tuzağına düşmeye neden olur.',
  },
  {
    id: 28,
    kategori: 'SQL',
    soru: "COALESCE(a, b, c) fonksiyonu ne döner?",
    secenekler: [
      'a, b ve c\'nin ortalaması',
      'Listeden NULL olmayan ilk değer',
      'Her zaman a\'yı döner',
      'a, b, c\'yi birleştirir (concatenate)',
    ],
    dogru: 1,
    aciklama: 'COALESCE() soldan sağa okur ve NULL olmayan ilk değeri döner. Tümü NULL ise NULL döner. Örneğin COALESCE(telefon, email, \'bilinmiyor\') sırasıyla telefon > email > sabit string tercih eder.',
  },
  {
    id: 29,
    kategori: 'Python',
    soru: "Büyük bir CSV dosyasını pandas'ta belleği verimli kullanarak okumak için hangi parametre kullanılır?",
    secenekler: [
      "pd.read_csv('dosya.csv', memory=True)",
      "pd.read_csv('dosya.csv', chunksize=10000)",
      "pd.read_csv('dosya.csv', optimize=True)",
      "pd.read_csv('dosya.csv', lazy=True)",
    ],
    dogru: 1,
    aciklama: "chunksize parametresi dosyayı belirtilen satır sayısında parçalar halinde okur. Her parça ayrı işlenebilir, tüm dosya belleğe yüklenmez. Ayrıca dtype parametresiyle sütun tipleri önceden belirtmek de bellek kullanımını azaltır.",
  },
  {
    id: 30,
    kategori: 'İstatistik',
    soru: 'Çarpık (skewed) bir dağılımda hangi merkezi eğilim ölçüsü en sağlıklı yorumu verir?',
    secenekler: [
      'Ortalama (mean)',
      'Medyan',
      'Mod',
      'Hepsi eşit derecede güvenilir',
    ],
    dogru: 1,
    aciklama: 'Çarpık dağılımlarda ortalama uç değerlerden etkilenerek yanıltıcı olabilir. Medyan, sıralanmış verinin ortasındaki değerdir ve uç değerlere karşı dayanıklıdır. Gelir dağılımı gibi sağa çarpık verilerde medyan daha anlamlıdır.',
  },
];

export function bugunuSorusu() {
  const baslangic = new Date('2026-01-01').getTime();
  const bugun = new Date();
  bugun.setHours(0, 0, 0, 0);
  const gunFarki = Math.floor((bugun.getTime() - baslangic) / 86400000);
  return sorular[gunFarki % sorular.length];
}

export function bugunKey() {
  const bugun = new Date();
  return `gsq_${bugun.getFullYear()}-${String(bugun.getMonth() + 1).padStart(2, '0')}-${String(bugun.getDate()).padStart(2, '0')}`;
}
