export const kategoriler = [
  { slug: 'interaktif', label: 'İnteraktif', emoji: '⚡', aciklama: 'Kavramları oynayarak öğren', renk: '#1D9E75', bg: '#E1F5EE', text: '#0F6E56', badgeClass: 'badge-interactive' },
  { slug: 'rehber',     label: 'Rehber',     emoji: '📖', aciklama: 'Adım adım öğren',           renk: '#7F77DD', bg: '#EEEDFE', text: '#534AB7', badgeClass: 'badge-guide' },
  { slug: 'arac',       label: 'Araç',       emoji: '🛠', aciklama: 'Hemen kullan',              renk: '#7F77DD', bg: '#EEEDFE', text: '#534AB7', badgeClass: 'badge-guide' },
  { slug: 'vaka',       label: 'Vaka',       emoji: '📊', aciklama: 'Gerçek veriyle analiz',     renk: '#e8a04a', bg: '#FAEEDA', text: '#854F0B', badgeClass: 'badge-case' },
  { slug: 'kariyer',    label: 'Kariyer',    emoji: '💼', aciklama: 'Kariyerinde bir adım öne',  renk: '#e8a04a', bg: '#FAEEDA', text: '#854F0B', badgeClass: 'badge-case' },
];

export const icerikler = [
  {
    href: '/veri-setleri',
    baslik: 'Türkiye Veri Seti Arşivi',
    ozet: '25+ açık veri kaynağı: ekonomi, deprem, hava, finans, spor. Kategorilere göre filtrele, hızlıca bul.',
    meta: 'Araç',
    kategori: 'arac',
    borderColor: '#7F77DD',
    icon: 'veri-setleri',
  },
  {
    href: '/yazilar/zaman-serisi',
    baslik: 'Zaman serisi: trendi, mevsimi, gürültüyü ayır',
    ozet: 'İnşacı, hareketli ortalama, ayrıştırma ve tahmin — 4 interaktif demo ile zaman serisi analizi.',
    meta: '12 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'zaman-serisi',
  },
  {
    href: '/yazilar/linear-regression',
    baslik: 'Linear regression: çizgiyi sen çiz',
    ozet: 'Noktaları sürükle, regresyon çizgisi ve R² anlık değişsin.',
    meta: '8 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'linear-regression',
  },
  {
    href: '/mulakat',
    baslik: 'Veri Bilimi Mülakat Simülatörü',
    ozet: '52 soru, 5 kategori: Python, SQL, İstatistik, ML, Davranışsal. Cevabı gör, kendini değerlendir, tekrar çalış.',
    meta: 'Araç',
    kategori: 'arac',
    borderColor: '#7F77DD',
    icon: 'mulakat',
  },
  {
    href: '/yazilar/churn-tahmini',
    baslik: 'Müşteri kaybı tahmini: kim gidecek, kime yatırım yapmalısın?',
    ozet: 'Sınıf dengesizliği, eşik optimizasyonu ve maliyet matrisi ile telco churn modeli. Kör kampanyadan %60 daha iyi.',
    meta: '18 dakika',
    kategori: 'vaka',
    borderColor: '#e8a04a',
    icon: 'churn',
  },
  {
    href: '/yazilar/kredi-shap',
    baslik: 'Kredi başvurun neden reddedildi? SHAP ile kara kutuyu aç',
    ozet: 'XGBoost modeli kararını nasıl alıyor? Her başvuru için adım adım açıklama, yasal zorunluluklar ve aksiyon önerileri.',
    meta: '15 dakika',
    kategori: 'vaka',
    borderColor: '#e8a04a',
    icon: 'kredi-shap',
  },
  {
    href: '/yazilar/izmir-kira-analizi',
    baslik: 'İzmir kira piyasası: 5.841 ilan, bir analist gözüyle',
    ozet: 'Hangi ilçe gerçekten pahalı? m² fiyatı hikayeyi nasıl değiştiriyor?',
    meta: '12 dakika',
    kategori: 'vaka',
    borderColor: '#e8a04a',
    icon: 'izmir-kira',
  },
  {
    href: '/yazilar/gradient-descent',
    baslik: 'Gradient descent: top yuvarlama oyunu',
    ozet: 'Öğrenme hızını ayarla, top minimuma insin.',
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'gradient-descent',
  },
  {
    href: '/yazilar/ab-test',
    baslik: 'A/B test anlamlılık hesaplayıcı',
    ozet: 'p-değeri, güven aralığı ve etki büyüklüğünü hesapla.',
    meta: 'interaktif araç',
    kategori: 'arac',
    borderColor: '#7F77DD',
    icon: 'ab-test',
  },
  {
    href: '/yazilar/kmeans',
    baslik: 'K-Means: müşterilerini kümele',
    ozet: "Centroid'lerin adım adım nasıl yer değiştirdiğini izle.",
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'kmeans',
  },
  {
    href: '/yazilar/ilk-90-gun',
    baslik: 'Veri analisti olarak ilk 90 günüm',
    ozet: '15 yıl sonra geriye bakınca keşke bilseydim dediklerim.',
    meta: '12 dakika',
    kategori: 'kariyer',
    borderColor: '#e8a04a',
    icon: 'ilk-90-gun',
  },
  {
    href: '/yazilar/confusion-matrix',
    baslik: 'Confusion matrix: eşik dansı',
    ozet: 'Eşiği kaydır, TP/FP/TN/FN ve ROC eğrisi canlı değişsin.',
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'confusion-matrix',
  },
  {
    href: '/yazilar/pandas-7-sey',
    baslik: "Pandas'ta en çok yanlış bilinen 7 şey",
    ozet: 'inplace, apply, merge, category dtype ve daha fazlası.',
    meta: '15 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'pandas-7-sey',
  },
  {
    href: '/yazilar/bias-variance',
    baslik: 'Bias-variance trade-off: ezber mi, genelleme mi?',
    ozet: 'Polinom derecesini artır, underfitting ve overfitting arasındaki geçişi izle.',
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'bias-variance',
  },
  {
    href: '/yazilar/feature-engineering',
    baslik: 'Feature engineering: modelden önce gelen sanat',
    ozet: 'Encoding, ölçekleme, zaman özellikleri, etkileşim ve seçim.',
    meta: '15 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'feature-engineering',
  },
  {
    href: '/yazilar/sql-temelleri',
    baslik: 'SQL temelleri: veri analistinin en önemli becerisi',
    ozet: 'SELECT, JOIN, GROUP BY, window fonksiyonlar — sıfırdan ileri seviyeye.',
    meta: '20 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'sql-temelleri',
  },
  {
    href: '/yazilar/cohort-analizi',
    baslik: 'SQL ile cohort analizi',
    ozet: 'Retention matrisi nasıl kurulur? CTE, window fonksiyonlar ve pivot — adım adım.',
    meta: '15 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'sql-temelleri',
  },
  {
    href: '/yazilar/sklearn-pipeline',
    baslik: 'Scikit-learn Pipeline\'ları',
    ozet: 'Veri sızıntısını önle, ColumnTransformer ile karışık veri tiplerini yönet, GridSearchCV ile entegre et.',
    meta: '20 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'feature-engineering',
  },
  {
    href: '/yazilar/databricks-rehberi',
    baslik: 'Databricks kullanım rehberi: Lakehouse\'dan MLflow\'a',
    ozet: 'Cluster kurulumundan Delta Lake\'e, PySpark\'tan MLflow Model Registry\'ye — Databricks ekosisteminin tam haritası.',
    meta: '30 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'etl-nedir',
  },
  {
    href: '/yazilar/sample-size',
    baslik: 'Sample size hesaplayıcı',
    ozet: 'A/B testi başlatmadan önce kaç kullanıcıya ihtiyacın var?',
    meta: 'interaktif araç',
    kategori: 'arac',
    borderColor: '#7F77DD',
    icon: 'sample-size',
  },
  {
    href: '/yazilar/sinir-agi',
    baslik: 'Sinir ağı visualizer: veri nasıl akar?',
    ozet: 'Katmanları ayarla, sinyal gönder, nöronların nasıl ateşlendiğini izle.',
    meta: '12 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'sinir-agi',
  },
  {
    href: '/yazilar/bezier',
    baslik: 'Bezier eğrisi: kontrol noktalarının dansı',
    ozet: 'Noktaları sürükle, De Casteljau adımlarını izle.',
    meta: 'geometri · 10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'bezier',
  },
  {
  href: '/yazilar/superlig-xg',
  baslik: "Süper Lig'de xG analizi: gol mü şans mı?",
  ozet: 'Icardi 25 gol attı ama beklentisi ne kadardı? Expected Goals ile futbol verisini keşfet.',
  meta: '12 dakika',
  kategori: 'vaka',
  borderColor: '#e8a04a',
  icon: 'superlig',
},
{
  href: '/python',
  baslik: 'Python Playground',
  ozet: 'Tarayıcında gerçek Python çalıştır. numpy, pandas, sklearn hazır.',
  meta: 'interaktif araç',
  kategori: 'arac',
  borderColor: '#7F77DD',
  icon: 'python',
},
{
  href: '/yazilar/rol-farklari',
  baslik: 'Veri analisti mi, data scientist mi, ML engineer mı?',
  ozet: '15 yıllık deneyimle rollerin farkları, maaş aralıkları ve geçiş yolları.',
  meta: '12 dakika',
  kategori: 'kariyer',
  borderColor: '#e8a04a',
  icon: 'kariyer',
},
{
  href: '/yazilar/veri-temizleme',
  baslik: 'Veri temizleme: kirli veriden temiz veriye',
  ozet: 'Eksik değerler, aykırı değerler, tip dönüşümleri — pandas ile veri temizlemenin tam rehberi.',
  meta: '20 dakika',
  kategori: 'rehber',
  borderColor: '#7F77DD',
  icon: 'pandas-7-sey',
},
{
  href: '/yazilar/bi-karsilastirma',
  baslik: 'Power BI vs Tableau vs Looker: hangisi sana uygun?',
  ozet: 'Fiyat, öğrenme eğrisi, güçlü/zayıf yanlar ve Türkiye iş piyasasında durum.',
  meta: '15 dakika',
  kategori: 'rehber',
  borderColor: '#7F77DD',
  icon: 'pandas-7-sey',
},
{
  href: '/yazilar/yol-haritasi',
  baslik: 'Veri analisti olma yol haritası',
  ozet: 'Sıfırdan veri analistine giden 10 adım. Her adımda ne öğreneceksin, ne kadar sürer, hangi kaynakları kullanacaksın.',
  meta: '10 adım · interaktif',
  kategori: 'kariyer',
  borderColor: '#1D9E75',
  icon: 'rol-farklari',
},
{
  href: '/sql',
  baslik: 'SQL Playground',
  ozet: '3 farklı veritabanı, gerçek SQL motoru. E-ticaret, IK ve spor verisiyle sorgu yaz.',
  meta: 'araç · sql.js',
  kategori: 'arac',
  borderColor: '#7F77DD',
  icon: 'sql-temelleri',
},
{
  href: '/yazilar/etl-nedir',
  baslik: 'ETL nedir? Veriyi taşımanın sistematik yolu',
  ozet: 'Extract, Transform, Load — ETL pipeline nedir, nasıl kurulur? Python ile gerçek ETL örnekleri.',
  meta: 'rehber · 18 dakika',
  kategori: 'rehber',
  borderColor: '#1D9E75',
  icon: 'veri-temizleme',
},
{
  href: '/yazilar/dbt-nedir',
  baslik: 'dbt nedir? Analytics engineering rehberi',
  ozet: 'dbt ile SQL tabanlı veri modelleme, staging-mart hiyerarşisi, testler ve CI/CD. Türkçe dbt rehberi.',
  meta: 'rehber · 20 dakika',
  kategori: 'rehber',
  borderColor: '#7F77DD',
  icon: 'etl-nedir',
},
{
  href: '/proje',
  baslik: 'Uçtan Uca Veri Analizi Projesi',
  ozet: 'Ham veri oluştur, temizle, dönüştür, görselleştir, raporla. 6 adımlı interaktif proje, 2 senaryo.',
  meta: 'interaktif · proje',
  kategori: 'interaktif',
  borderColor: '#1D9E75',
  icon: 'linear-regression',
},
{
  href: '/yazilar/portfolyo',
  baslik: 'Veri analisti portföyü nasıl hazırlanır?',
  ozet: 'GitHub, Kaggle, proje seçimi ve işe alımcıların gerçekten baktığı şeyler.',
  meta: 'kariyer · 15 dakika',
  kategori: 'kariyer',
  borderColor: '#e8a04a',
  icon: 'portfolyo',
},
{
  href: '/yazilar/mulakat-sql',
  baslik: 'Mülakatta sorulan 10 SQL sorusu',
  ozet: 'Senaryo, çözüm ve sık yapılan hatalarla gerçek mülakat soruları.',
  meta: 'kariyer · 20 dakika',
  kategori: 'kariyer',
  borderColor: '#e8a04a',
  icon: 'mulakat-sql',
},
{
  href: '/yazilar/decision-tree',
  baslik: 'Decision tree: ağacı sen büyüt',
  ozet: 'Bölme eşiklerini sürükle, Gini impurity\'nin nasıl düştüğünü izle.',
  meta: 'interaktif · 10 dakika',
  kategori: 'interaktif',
  borderColor: '#1D9E75',
  icon: 'decision-tree',
},
{
  href: '/yazilar/linkedin-profili',
  baslik: 'Veri analisti LinkedIn profili nasıl olmalı?',
  ozet: 'Headline, about bölümü, deneyim yazımı ve işe alımcıların dikkat ettiği şeyler.',
  meta: 'kariyer · 12 dakika',
  kategori: 'kariyer',
  borderColor: '#e8a04a',
  icon: 'linkedin',
},
{
  href: '/yazilar/cloud-rehberi',
  baslik: 'Veri bilimcisi için cloud: GCP mi AWS mi?',
  ozet: 'BigQuery vs Redshift, Vertex AI vs SageMaker. Hangi servisi ne zaman kullanırsın?',
  meta: 'rehber · 18 dakika',
  kategori: 'rehber',
  borderColor: '#7F77DD',
  icon: 'cloud',
},
{
  href: '/yazilar/merkezi-limit-teoremi',
  baslik: 'Merkezi Limit Teoremi: her şey eninde sonunda normal dağılır',
  ozet: 'Dağılım seç, örnekle, ortalamaların histogramı gözünün önünde normale yaklaşsın.',
  meta: 'interaktif · 10 dakika',
  kategori: 'interaktif',
  borderColor: '#1D9E75',
  icon: 'clt',
},
{
  href: '/yazilar/random-forest',
  baslik: 'Random Forest: yüz ağaç bir orman yapar',
  ozet: 'Slider ile ağaç ekle, karar sınırı nasıl yumuşuyor izle. Test noktasını sürükle, oylama canlı değişsin.',
  meta: 'interaktif · 14 dakika',
  kategori: 'interaktif',
  borderColor: '#1D9E75',
  icon: 'forest',
},
{
  href: '/yazilar/naive-bayes',
  baslik: 'Naive Bayes: spam filtresi kendi kendine nasıl öğrenir?',
  ozet: 'Kelimeleri seç, spam olasılığını canlı gör. Bayes teoremi adım adım.',
  meta: 'interaktif · 12 dakika',
  kategori: 'interaktif',
  borderColor: '#1D9E75',
  icon: 'bayes',
},
{
  href: '/yazilar/spotify-turkiye',
  baslik: 'Spotify Türkiye: 82 milyon kulak, ne dinliyor?',
  ozet: 'Tür dağılımı, ses özellikleri, gece yarısı arabesk zirvelemesi ve yaz pop patlaması.',
  meta: '12 dakika',
  kategori: 'vaka',
  borderColor: '#e8a04a',
  icon: 'spotify',
},
{
  href: '/yazilar/anscombe',
  baslik: "Anscombe'un Dörtlüsü: sayılar aynı, gerçek farklı",
  ozet: '4 veri seti, birebir aynı istatistikler — ama grafikleri bambaşka. Görselleştirme neden zorunlu?',
  meta: 'interaktif · 10 dakika',
  kategori: 'interaktif',
  borderColor: '#1D9E75',
  icon: 'anscombe',
},
{
  href: '/yazilar/veri-dedektifi',
  baslik: 'Veri dedektifi: gelir düşüşünün sebebini bul',
  ozet: 'FikirzadeTech geliri %28 düştü. 8 panel incele, kanıtları topla, kök nedeni bul.',
  meta: 'interaktif · soruşturma oyunu',
  kategori: 'interaktif',
  borderColor: '#1D9E75',
  icon: 'dedektif',
},
{
  href: '/yazilar/deprem-analizi',
  baslik: 'Türkiye deprem verisi: 1900-2024 ne anlatıyor?',
  ozet: 'Bölgesel dağılım, Gutenberg-Richter yasası, derinlik-büyüklük ilişkisi ve 125 yılın büyük depremleri.',
  meta: 'vaka · 14 dakika',
  kategori: 'vaka',
  borderColor: '#e8a04a',
  icon: 'deprem',
},
{
  href: '/csv',
  baslik: 'CSV Analiz Aracı',
  ozet: 'CSV yapıştır ya da yükle. Veri tipleri, eksik değerler, istatistikler ve dağılımlar anında.',
  meta: 'araç · tarayıcıda çalışır',
  kategori: 'arac',
  borderColor: '#7F77DD',
  icon: 'csv',
},
{
  href: '/renk',
  baslik: 'Renk Paleti Seçici',
  ozet: 'Kategorik, sıralı, ayrışık ve renk körü dostu paletler. Tıkla, önizle, hex kodu kopyala.',
  meta: 'araç · görselleştirme',
  kategori: 'arac',
  borderColor: '#7F77DD',
  icon: 'renk',
},
];
