export const kategoriler = [
  { slug: 'interaktif', label: 'İnteraktif', emoji: '⚡', aciklama: 'Kavramları oynayarak öğren', renk: '#1D9E75', bg: '#E1F5EE', text: '#0F6E56', badgeClass: 'badge-interactive' },
  { slug: 'rehber',     label: 'Rehber',     emoji: '📖', aciklama: 'Adım adım öğren',           renk: '#7F77DD', bg: '#EEEDFE', text: '#534AB7', badgeClass: 'badge-guide' },
  { slug: 'arac',       label: 'Araç',       emoji: '🛠', aciklama: 'Hemen kullan',              renk: '#7F77DD', bg: '#EEEDFE', text: '#534AB7', badgeClass: 'badge-guide' },
  { slug: 'vaka',       label: 'Vaka',       emoji: '📊', aciklama: 'Gerçek veriyle analiz',     renk: '#e8a04a', bg: '#FAEEDA', text: '#854F0B', badgeClass: 'badge-case' },
  { slug: 'kariyer',    label: 'Kariyer',    emoji: '💼', aciklama: 'Kariyerinde bir adım öne',  renk: '#e8a04a', bg: '#FAEEDA', text: '#854F0B', badgeClass: 'badge-case' },
];

export const icerikler = [
  {
    href: '/yazilar/linear-regression',
    baslik: 'Linear regression: çizgiyi sen çiz',
    ozet: 'Noktaları sürükle, regresyon çizgisi ve R² anlık değişsin.',
    meta: '8 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'linear-regression',
  },
  {
    href: '/yazilar/izmir-kira-analizi',
    baslik: 'İzmir kira piyasası: 5.841 ilan, bir analist gözüyle',
    ozet: 'Hangi ilçe gerçekten pahalı? m² fiyatı hikayeyi nasıl değiştiriyor?',
    meta: '12 dakika',
    kategori: 'vaka',
    borderColor: '#e8a04a',
    icon: 'izmir-kira',
  },
  {
    href: '/yazilar/gradient-descent',
    baslik: 'Gradient descent: top yuvarlama oyunu',
    ozet: 'Öğrenme hızını ayarla, top minimuma insin.',
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'gradient-descent',
  },
  {
    href: '/yazilar/ab-test',
    baslik: 'A/B test anlamlılık hesaplayıcı',
    ozet: 'p-değeri, güven aralığı ve etki büyüklüğünü hesapla.',
    meta: 'interaktif araç',
    kategori: 'arac',
    borderColor: '#7F77DD',
    icon: 'ab-test',
  },
  {
    href: '/yazilar/kmeans',
    baslik: 'K-Means: müşterilerini kümele',
    ozet: "Centroid'lerin adım adım nasıl yer değiştirdiğini izle.",
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'kmeans',
  },
  {
    href: '/yazilar/ilk-90-gun',
    baslik: 'Veri analisti olarak ilk 90 günüm',
    ozet: '15 yıl sonra geriye bakınca keşke bilseydim dediklerim.',
    meta: '12 dakika',
    kategori: 'kariyer',
    borderColor: '#e8a04a',
    icon: 'ilk-90-gun',
  },
  {
    href: '/yazilar/confusion-matrix',
    baslik: 'Confusion matrix: eşik dansı',
    ozet: 'Eşiği kaydır, TP/FP/TN/FN ve ROC eğrisi canlı değişsin.',
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'confusion-matrix',
  },
  {
    href: '/yazilar/pandas-7-sey',
    baslik: "Pandas'ta en çok yanlış bilinen 7 şey",
    ozet: 'inplace, apply, merge, category dtype ve daha fazlası.',
    meta: '15 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'pandas-7-sey',
  },
  {
    href: '/yazilar/bias-variance',
    baslik: 'Bias-variance trade-off: ezber mi, genelleme mi?',
    ozet: 'Polinom derecesini artır, underfitting ve overfitting arasındaki geçişi izle.',
    meta: '10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'bias-variance',
  },
  {
    href: '/yazilar/feature-engineering',
    baslik: 'Feature engineering: modelden önce gelen sanat',
    ozet: 'Encoding, ölçekleme, zaman özellikleri, etkileşim ve seçim.',
    meta: '15 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'feature-engineering',
  },
  {
    href: '/yazilar/sql-temelleri',
    baslik: 'SQL temelleri: veri analistinin en önemli becerisi',
    ozet: 'SELECT, JOIN, GROUP BY, window fonksiyonlar — sıfırdan ileri seviyeye.',
    meta: '20 dakika',
    kategori: 'rehber',
    borderColor: '#7F77DD',
    icon: 'sql-temelleri',
  },
  {
    href: '/yazilar/sample-size',
    baslik: 'Sample size hesaplayıcı',
    ozet: 'A/B testi başlatmadan önce kaç kullanıcıya ihtiyacın var?',
    meta: 'interaktif araç',
    kategori: 'arac',
    borderColor: '#7F77DD',
    icon: 'sample-size',
  },
  {
    href: '/yazilar/sinir-agi',
    baslik: 'Sinir ağı visualizer: veri nasıl akar?',
    ozet: 'Katmanları ayarla, sinyal gönder, nöronların nasıl ateşlendiğini izle.',
    meta: '12 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'sinir-agi',
  },
  {
    href: '/yazilar/bezier',
    baslik: 'Bezier eğrisi: kontrol noktalarının dansı',
    ozet: 'Noktaları sürükle, De Casteljau adımlarını izle.',
    meta: 'geometri · 10 dakika',
    kategori: 'interaktif',
    borderColor: '#1D9E75',
    icon: 'bezier',
  },
  {
  href: '/yazilar/superlig-xg',
  baslik: "Süper Lig'de xG analizi: gol mü şans mı?",
  ozet: 'Icardi 25 gol attı ama beklentisi ne kadardı? Expected Goals ile futbol verisini keşfet.',
  meta: '12 dakika',
  kategori: 'vaka',
  borderColor: '#e8a04a',
  icon: 'superlig',
},
{
  href: '/python',
  baslik: 'Python Playground',
  ozet: 'Tarayıcında gerçek Python çalıştır. numpy, pandas, sklearn hazır.',
  meta: 'interaktif araç',
  kategori: 'arac',
  borderColor: '#7F77DD',
  icon: 'python',
},
{
  href: '/yazilar/rol-farklari',
  baslik: 'Veri analisti mi, data scientist mi, ML engineer mı?',
  ozet: '15 yıllık deneyimle rollerin farkları, maaş aralıkları ve geçiş yolları.',
  meta: '12 dakika',
  kategori: 'kariyer',
  borderColor: '#e8a04a',
  icon: 'kariyer',
},
{
  href: '/yazilar/veri-temizleme',
  baslik: 'Veri temizleme: kirli veriden temiz veriye',
  ozet: 'Eksik değerler, aykırı değerler, tip dönüşümleri — pandas ile veri temizlemenin tam rehberi.',
  meta: '20 dakika',
  kategori: 'rehber',
  borderColor: '#7F77DD',
  icon: 'pandas-7-sey',
},
{
  href: '/yazilar/bi-karsilastirma',
  baslik: 'Power BI vs Tableau vs Looker: hangisi sana uygun?',
  ozet: 'Fiyat, öğrenme eğrisi, güçlü/zayıf yanlar ve Türkiye iş piyasasında durum.',
  meta: '15 dakika',
  kategori: 'rehber',
  borderColor: '#7F77DD',
  icon: 'pandas-7-sey',
},
{
  href: '/yazilar/yol-haritasi',
  baslik: 'Veri analisti olma yol haritası',
  ozet: 'Sıfırdan veri analistine giden 10 adım. Her adımda ne öğreneceksin, ne kadar sürer, hangi kaynakları kullanacaksın.',
  meta: '10 adım · interaktif',
  kategori: 'kariyer',
  borderColor: '#1D9E75',
  icon: 'rol-farklari',
},
];
