export const veriKategorileri = [
  { slug: 'tumu',    label: 'Tümü',      emoji: '🗂️' },
  { slug: 'ekonomi', label: 'Ekonomi',   emoji: '📈' },
  { slug: 'nufus',   label: 'Nüfus',     emoji: '👥' },
  { slug: 'deprem',  label: 'Deprem',    emoji: '🌍' },
  { slug: 'hava',    label: 'Hava/İklim',emoji: '🌤️' },
  { slug: 'finans',  label: 'Finans',    emoji: '💹' },
  { slug: 'saglik',  label: 'Sağlık',    emoji: '🏥' },
  { slug: 'ulasim',  label: 'Ulaşım',    emoji: '🚌' },
  { slug: 'enerji',  label: 'Enerji',    emoji: '⚡' },
  { slug: 'spor',    label: 'Spor',      emoji: '⚽' },
  { slug: 'genel',   label: 'Portaller', emoji: '🌐' },
];

export const veriSetleri = [
  // GENEL PORTALLER
  {
    id: 'data-gov-tr',
    baslik: 'Türkiye Açık Veri Portalı',
    kaynak: 'data.gov.tr',
    aciklama: 'Bakanlıklar ve kamu kurumlarından 10.000+ açık veri seti. Nüfus, ekonomi, eğitim, sağlık ve daha fazlası tek çatı altında.',
    kategori: 'genel',
    format: ['CSV', 'XLSX', 'JSON', 'API'],
    guncelleme: 'Sürekli',
    url: 'https://data.gov.tr',
    oneCikan: true,
  },
  {
    id: 'ibb-acik-veri',
    baslik: 'İBB Açık Veri Portalı',
    kaynak: 'data.ibb.gov.tr',
    aciklama: 'İstanbul\'a ait ulaşım, nüfus, kültür, çevre verileri. Metroda yolcu sayısı, hava kalitesi, trafik yoğunluğu gibi detaylı şehir verileri.',
    kategori: 'genel',
    format: ['CSV', 'JSON', 'API', 'GeoJSON'],
    guncelleme: 'Günlük/Haftalık',
    url: 'https://data.ibb.gov.tr',
    oneCikan: true,
  },
  {
    id: 'ankara-acik-veri',
    baslik: 'Ankara Büyükşehir Açık Veri',
    kaynak: 'acikveri.ankara.bel.tr',
    aciklama: 'Ankara\'ya ait ulaşım, kentsel dönüşüm, nüfus ve çevre verileri. EGO güzergah, durak ve yolcu verilerini içerir.',
    kategori: 'genel',
    format: ['CSV', 'JSON', 'XLSX'],
    guncelleme: 'Aylık',
    url: 'https://acikveri.ankara.bel.tr',
    oneCikan: false,
  },

  // EKONOMİ
  {
    id: 'tuik-ana',
    baslik: 'TÜİK İstatistik Veritabanı',
    kaynak: 'tuik.gov.tr',
    aciklama: 'Türkiye İstatistik Kurumu\'nun tüm istatistik verileri: GSYH, enflasyon, işsizlik, dış ticaret, nüfus ve daha fazlası. En kapsamlı resmi kaynak.',
    kategori: 'ekonomi',
    format: ['XLSX', 'CSV', 'API'],
    guncelleme: 'Aylık/Yıllık',
    url: 'https://data.tuik.gov.tr',
    oneCikan: true,
  },
  {
    id: 'tcmb-evds',
    baslik: 'TCMB Elektronik Veri Dağıtım Sistemi',
    kaynak: 'tcmb.gov.tr',
    aciklama: 'Merkez Bankası\'nın tüm ekonomik verileri: döviz kurları, faiz oranları, enflasyon, ödemeler dengesi. API erişimi ile otomatik veri çekme imkânı.',
    kategori: 'ekonomi',
    format: ['CSV', 'XLSX', 'JSON', 'API'],
    guncelleme: 'Günlük',
    url: 'https://evds2.tcmb.gov.tr',
    oneCikan: true,
  },
  {
    id: 'world-bank-tr',
    baslik: 'World Bank — Türkiye Verileri',
    kaynak: 'data.worldbank.org',
    aciklama: '1960\'tan günümüze 1.400+ ekonomik ve kalkınma göstergesi. GSYH büyümesi, yoksulluk oranı, eğitim harcamaları, CO2 emisyonu. API ile erişilebilir.',
    kategori: 'ekonomi',
    format: ['CSV', 'XLSX', 'JSON', 'API'],
    guncelleme: 'Yıllık',
    url: 'https://data.worldbank.org/country/turkey',
    oneCikan: false,
  },
  {
    id: 'imf-tr',
    baslik: 'IMF — Türkiye Verileri',
    kaynak: 'imf.org',
    aciklama: 'IMF\'nin Türkiye için yayımladığı makroekonomik veriler. Bütçe dengesi, kamu borcu, cari işlemler açığı ve ödemeler dengesi.',
    kategori: 'ekonomi',
    format: ['CSV', 'XLSX'],
    guncelleme: 'Yıllık',
    url: 'https://www.imf.org/en/Countries/TUR',
    oneCikan: false,
  },

  // NÜFUS
  {
    id: 'tuik-adnks',
    baslik: 'Adrese Dayalı Nüfus Kayıt Sistemi',
    kaynak: 'tuik.gov.tr',
    aciklama: 'İl ve ilçe bazında nüfus verileri, cinsiyet ve yaş dağılımı, nüfus hareketleri. 2007\'den günümüze yıllık güncellemeler.',
    kategori: 'nufus',
    format: ['XLSX', 'CSV'],
    guncelleme: 'Yıllık',
    url: 'https://data.tuik.gov.tr/Kategori/GetKategori?p=nufus-ve-demografi-109',
    oneCikan: true,
  },
  {
    id: 'tuik-goc',
    baslik: 'Göç İstatistikleri',
    kaynak: 'tuik.gov.tr',
    aciklama: 'İç ve dış göç verileri. Şehirleşme oranları, il bazında net göç hızları, uluslararası göç akışları.',
    kategori: 'nufus',
    format: ['XLSX'],
    guncelleme: 'Yıllık',
    url: 'https://data.tuik.gov.tr/Kategori/GetKategori?p=nufus-ve-demografi-109',
    oneCikan: false,
  },
  {
    id: 'osym-istatistik',
    baslik: 'ÖSYM Sınav İstatistikleri',
    kaynak: 'osym.gov.tr',
    aciklama: 'YKS, KPSS, ALES sonuç istatistikleri. Puan ortalamaları, tercih verileri, il bazında katılım oranları.',
    kategori: 'nufus',
    format: ['PDF', 'XLSX'],
    guncelleme: 'Yıllık',
    url: 'https://www.osym.gov.tr/TR,6552/istatistikler.html',
    oneCikan: false,
  },

  // DEPREM
  {
    id: 'afad-deprem',
    baslik: 'AFAD Deprem Kataloğu',
    kaynak: 'afad.gov.tr',
    aciklama: 'Türkiye\'de meydana gelen depremlerin tam listesi. Tarih, saat, koordinat, derinlik ve büyüklük bilgileri. Gerçek zamanlı ve geçmiş veriler.',
    kategori: 'deprem',
    format: ['CSV', 'API'],
    guncelleme: 'Gerçek Zamanlı',
    url: 'https://deprem.afad.gov.tr',
    oneCikan: true,
  },
  {
    id: 'kandilli',
    baslik: 'Kandilli Rasathanesi Deprem Verileri',
    kaynak: 'koeri.boun.edu.tr',
    aciklama: '1900\'lerden günümüze deprem kayıtları. KRDAE tarafından sağlanan katalog verileri, özellikle Marmara Bölgesi için detaylı kayıtlar.',
    kategori: 'deprem',
    format: ['TXT', 'CSV'],
    guncelleme: 'Günlük',
    url: 'http://www.koeri.boun.edu.tr/sismo/2/deprem-verileri',
    oneCikan: false,
  },
  {
    id: 'usgs-turkey',
    baslik: 'USGS Earthquake Catalog — Türkiye',
    kaynak: 'earthquake.usgs.gov',
    aciklama: 'ABD Jeoloji Araştırmaları Merkezi\'nin Türkiye deprem verileri. M2.5+ depremler, interaktif harita ve API desteği. Uluslararası standart format.',
    kategori: 'deprem',
    format: ['CSV', 'GeoJSON', 'API'],
    guncelleme: 'Gerçek Zamanlı',
    url: 'https://earthquake.usgs.gov/earthquakes/search',
    oneCikan: false,
  },

  // HAVA / İKLİM
  {
    id: 'mgm',
    baslik: 'MGM Meteoroloji Verileri',
    kaynak: 'mgm.gov.tr',
    aciklama: 'Türkiye genelinde 1.300+ istasyondan sıcaklık, yağış, nem, rüzgar verileri. Tarihsel iklim ortalamaları ve anlık gözlem verileri.',
    kategori: 'hava',
    format: ['CSV', 'XLSX'],
    guncelleme: 'Günlük',
    url: 'https://www.mgm.gov.tr/veridegerlendirme/il-ve-ilceler-istatistik.aspx',
    oneCikan: true,
  },
  {
    id: 'open-meteo',
    baslik: 'Open-Meteo Hava Verisi API',
    kaynak: 'open-meteo.com',
    aciklama: 'Türkiye dahil tüm dünya için ücretsiz hava durumu API\'si. 80 yıllık tarihsel veri, saatlik granülerlik. Projeler için ideal.',
    kategori: 'hava',
    format: ['JSON', 'CSV', 'API'],
    guncelleme: 'Saatlik',
    url: 'https://open-meteo.com',
    oneCikan: false,
  },

  // FİNANS
  {
    id: 'bist',
    baslik: 'Borsa İstanbul Verileri',
    kaynak: 'borsaistanbul.com',
    aciklama: 'BIST100 ve tüm hisse senetleri için günlük fiyat, hacim ve endeks verileri. Tarihsel veri CSV olarak indirilebilir.',
    kategori: 'finans',
    format: ['CSV', 'XLSX'],
    guncelleme: 'Günlük',
    url: 'https://www.borsaistanbul.com/tr/sayfa/1151/veriler',
    oneCikan: true,
  },
  {
    id: 'bddk',
    baslik: 'BDDK Bankacılık Verileri',
    kaynak: 'bddk.org.tr',
    aciklama: 'Bankacılık sektörü verileri: kredi hacmi, mevduat, takipteki alacaklar, banka bilançoları. Aylık ve çeyreklik raporlar.',
    kategori: 'finans',
    format: ['XLSX', 'PDF'],
    guncelleme: 'Aylık',
    url: 'https://www.bddk.org.tr/Istatistiki-Veriler',
    oneCikan: false,
  },
  {
    id: 'investing-tr',
    baslik: 'Yahoo Finance — Türk Hisse Senetleri',
    kaynak: 'finance.yahoo.com',
    aciklama: 'Python\'da yfinance kütüphanesiyle Türk şirketleri dahil dünya genelindeki hisse senedi verilerini çek. Ticker formatı: "THYAO.IS".',
    kategori: 'finans',
    format: ['Python API', 'CSV'],
    guncelleme: 'Günlük',
    url: 'https://finance.yahoo.com',
    oneCikan: false,
  },

  // SAĞLIK
  {
    id: 'saglik-bakanlik',
    baslik: 'Sağlık Bakanlığı İstatistikleri',
    kaynak: 'saglik.gov.tr',
    aciklama: 'Yıllık sağlık istatistikleri: hasta sayıları, hastane kapasitesi, hastalık istatistikleri, ölüm nedenleri, anne-çocuk sağlığı verileri.',
    kategori: 'saglik',
    format: ['PDF', 'XLSX'],
    guncelleme: 'Yıllık',
    url: 'https://www.saglik.gov.tr/TR,11588/istatistikler.html',
    oneCikan: true,
  },
  {
    id: 'who-turkey',
    baslik: 'WHO — Türkiye Sağlık Verileri',
    kaynak: 'who.int',
    aciklama: 'Dünya Sağlık Örgütü\'nün Türkiye için sağlık göstergeleri. Yaşam beklentisi, infant mortalite, obezite, sigara kullanımı gibi karşılaştırmalı veriler.',
    kategori: 'saglik',
    format: ['CSV', 'API'],
    guncelleme: 'Yıllık',
    url: 'https://www.who.int/countries/tur',
    oneCikan: false,
  },

  // ULAŞIM
  {
    id: 'ibb-metro',
    baslik: 'İBB Metro Yolcu Sayıları',
    kaynak: 'data.ibb.gov.tr',
    aciklama: 'İstanbul metro, metrobüs ve tramvay hatlarında günlük yolcu sayıları. Saatlik ve hat bazında ayrıntılar. Toplu taşıma analizi için ideal.',
    kategori: 'ulasim',
    format: ['CSV', 'JSON', 'API'],
    guncelleme: 'Aylık',
    url: 'https://data.ibb.gov.tr/dataset/metro-ag-yolcu-sayilari',
    oneCikan: true,
  },
  {
    id: 'ulastirma-bakanlik',
    baslik: 'Ulaştırma Bakanlığı Verileri',
    kaynak: 'uab.gov.tr',
    aciklama: 'Karayolu, demiryolu, havayolu ve deniz taşımacılığı istatistikleri. Uçuş verileri, liman yük miktarları, trafik kazası istatistikleri.',
    kategori: 'ulasim',
    format: ['XLSX', 'PDF'],
    guncelleme: 'Yıllık',
    url: 'https://www.uab.gov.tr/istatistikler',
    oneCikan: false,
  },

  // ENERJİ
  {
    id: 'epias',
    baslik: 'EPİAŞ Şeffaflık Platformu',
    kaynak: 'seffaflik.epias.com.tr',
    aciklama: 'Türkiye elektrik piyasası verileri: günlük üretim/tüketim, kaynak bazlı elektrik üretimi (güneş, rüzgar, hidroelektrik), spot fiyatlar. API erişimi mevcut.',
    kategori: 'enerji',
    format: ['CSV', 'XLSX', 'API'],
    guncelleme: 'Saatlik',
    url: 'https://seffaflik.epias.com.tr',
    oneCikan: true,
  },
  {
    id: 'yegm',
    baslik: 'YEGM Yenilenebilir Enerji Verileri',
    kaynak: 'enerji.gov.tr',
    aciklama: 'Türkiye\'nin yenilenebilir enerji kapasitesi, güneş/rüzgar potansiyel atlasları, kurulu güç istatistikleri.',
    kategori: 'enerji',
    format: ['PDF', 'XLSX'],
    guncelleme: 'Yıllık',
    url: 'https://www.enerji.gov.tr/tr-TR/Sayfalar/Yenilenebilir',
    oneCikan: false,
  },

  // SPOR
  {
    id: 'fbref-superlig',
    baslik: 'FBref — Süper Lig İstatistikleri',
    kaynak: 'fbref.com',
    aciklama: 'Süper Lig\'de oyuncu ve takım istatistikleri: gol, asist, pas yüzdesi, xG, pressings ve daha fazlası. Veri bilimi projelerinin favorisi.',
    kategori: 'spor',
    format: ['CSV (kopyala-yapıştır)', 'Web Scraping'],
    guncelleme: 'Haftalık',
    url: 'https://fbref.com/en/comps/26/Super-Lig-Stats',
    oneCikan: true,
  },
  {
    id: 'transfermarkt',
    baslik: 'Transfermarkt — Türk Futbol Verileri',
    kaynak: 'transfermarkt.com.tr',
    aciklama: 'Oyuncu değerleri, transfer geçmişi, sözleşme bilgileri, ilk 11 verileri. Süper Lig ve alt liglerden kapsamlı futbolcu profilleri.',
    kategori: 'spor',
    format: ['Web Scraping'],
    guncelleme: 'Haftalık',
    url: 'https://www.transfermarkt.com.tr',
    oneCikan: false,
  },
];
